# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.template_preview_request import TemplatePreviewRequest

class TestTemplatePreviewRequest(unittest.TestCase):
    """TemplatePreviewRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplatePreviewRequest:
        """Test TemplatePreviewRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplatePreviewRequest`
        """
        model = TemplatePreviewRequest()
        if include_optional:
            return TemplatePreviewRequest(
                sample_context = {
                    'key' : null
                    }
            )
        else:
            return TemplatePreviewRequest(
        )
        """

    def testTemplatePreviewRequest(self):
        """Test TemplatePreviewRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
