# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc10
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.insight_card import InsightCard

class TestInsightCard(unittest.TestCase):
    """InsightCard unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InsightCard:
        """Test InsightCard
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InsightCard`
        """
        model = InsightCard()
        if include_optional:
            return InsightCard(
                id = '',
                type = 'insight',
                title = '',
                description = '',
                cta_label = '',
                cta_route = '',
                priority = 'high',
                icon = '',
                icon_color = '',
                icon_bg = '',
                persona = [
                    ''
                    ],
                metric_value = ''
            )
        else:
            return InsightCard(
                id = '',
                type = 'insight',
                title = '',
                description = '',
                cta_label = '',
                cta_route = '',
                priority = 'high',
                icon = '',
                icon_color = '',
                icon_bg = '',
                persona = [
                    ''
                    ],
        )
        """

    def testInsightCard(self):
        """Test InsightCard"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
