# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.price_session_response import PriceSessionResponse

class TestPriceSessionResponse(unittest.TestCase):
    """PriceSessionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PriceSessionResponse:
        """Test PriceSessionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PriceSessionResponse`
        """
        model = PriceSessionResponse()
        if include_optional:
            return PriceSessionResponse(
                quote_id = '',
                quote_version = 56,
                pricing_snapshot_id = '',
                normalized_input = {
                    'key' : null
                    },
                priced_output = {
                    'key' : null
                    },
                pricing_trace = {
                    'key' : null
                    },
                pricing_trace_digest = '',
                source_versions = {
                    'key' : null
                    },
                currency = 'USD',
                subtotal_micros = 56,
                discount_micros = 56,
                total_micros = 56
            )
        else:
            return PriceSessionResponse(
                quote_id = '',
                quote_version = 56,
                pricing_snapshot_id = '',
                normalized_input = {
                    'key' : null
                    },
                priced_output = {
                    'key' : null
                    },
                pricing_trace = {
                    'key' : null
                    },
                pricing_trace_digest = '',
                source_versions = {
                    'key' : null
                    },
                subtotal_micros = 56,
                discount_micros = 56,
                total_micros = 56,
        )
        """

    def testPriceSessionResponse(self):
        """Test PriceSessionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
