# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc8
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.feature_margin_item import FeatureMarginItem

class TestFeatureMarginItem(unittest.TestCase):
    """FeatureMarginItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FeatureMarginItem:
        """Test FeatureMarginItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FeatureMarginItem`
        """
        model = FeatureMarginItem()
        if include_optional:
            return FeatureMarginItem(
                feature_id = '',
                total_valued_burn = '',
                total_cost = '',
                margin = '',
                margin_pct = '',
                margin_reason = '',
                billing_event_count = 56
            )
        else:
            return FeatureMarginItem(
                feature_id = '',
                total_valued_burn = '',
                total_cost = '',
                margin = '',
                margin_pct = '',
                margin_reason = '',
                billing_event_count = 56,
        )
        """

    def testFeatureMarginItem(self):
        """Test FeatureMarginItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
