# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.billing_party_replace_update import BillingPartyReplaceUpdate

class TestBillingPartyReplaceUpdate(unittest.TestCase):
    """BillingPartyReplaceUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillingPartyReplaceUpdate:
        """Test BillingPartyReplaceUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillingPartyReplaceUpdate`
        """
        model = BillingPartyReplaceUpdate()
        if include_optional:
            return BillingPartyReplaceUpdate(
                key = '0',
                name = '',
                tax_id = moolabs.models.billing_party_tax_identity.BillingPartyTaxIdentity(
                    code = null, ),
                addresses = [
                    moolabs.models.address.Address(
                        country = null, 
                        postal_code = '', 
                        state = '', 
                        city = '', 
                        line1 = '', 
                        line2 = '', 
                        phone_number = '', )
                    ]
            )
        else:
            return BillingPartyReplaceUpdate(
        )
        """

    def testBillingPartyReplaceUpdate(self):
        """Test BillingPartyReplaceUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
