# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.api.governance_api import GovernanceApi


class TestGovernanceApi(unittest.TestCase):
    """GovernanceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GovernanceApi()

    def tearDown(self) -> None:
        pass

    def test_create_strategy_endpoint(self) -> None:
        """Test case for create_strategy_endpoint

        Create Strategy Endpoint
        """
        pass

    def test_delete_strategy_endpoint(self) -> None:
        """Test case for delete_strategy_endpoint

        Delete Strategy Endpoint
        """
        pass

    def test_get_cash_app_config_endpoint_v1_arc(self) -> None:
        """Test case for get_cash_app_config_endpoint_v1_arc

        Get Cash App Config Endpoint
        """
        pass

    def test_get_strategy_endpoint(self) -> None:
        """Test case for get_strategy_endpoint

        Get Strategy Endpoint
        """
        pass

    def test_kill_switch_endpoint_v1_arc(self) -> None:
        """Test case for kill_switch_endpoint_v1_arc

        Kill Switch Endpoint
        """
        pass

    def test_list_evaluations_endpoint(self) -> None:
        """Test case for list_evaluations_endpoint

        List Evaluations Endpoint
        """
        pass

    def test_list_policies_endpoint_v1(self) -> None:
        """Test case for list_policies_endpoint_v1

        List Policies Endpoint
        """
        pass

    def test_list_strategies_endpoint(self) -> None:
        """Test case for list_strategies_endpoint

        List Strategies Endpoint
        """
        pass

    def test_shadow_mode_endpoint_v1_arc(self) -> None:
        """Test case for shadow_mode_endpoint_v1_arc

        Shadow Mode Endpoint
        """
        pass

    def test_strategy_preview_endpoint_v1(self) -> None:
        """Test case for strategy_preview_endpoint_v1

        Strategy Preview Endpoint
        """
        pass

    def test_update_cash_app_config_endpoint_v1_arc(self) -> None:
        """Test case for update_cash_app_config_endpoint_v1_arc

        Update Cash App Config Endpoint
        """
        pass

    def test_update_policy_endpoint_v1(self) -> None:
        """Test case for update_policy_endpoint_v1

        Update Policy Endpoint
        """
        pass

    def test_update_strategy_endpoint(self) -> None:
        """Test case for update_strategy_endpoint

        Update Strategy Endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
