# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.api.outbox_api import OutboxApi


class TestOutboxApi(unittest.TestCase):
    """OutboxApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OutboxApi()

    def tearDown(self) -> None:
        pass

    def test_list_outbox_events_endpoint(self) -> None:
        """Test case for list_outbox_events_endpoint

        List Outbox Events Endpoint
        """
        pass

    def test_process_outbox_endpoint(self) -> None:
        """Test case for process_outbox_endpoint

        Process Outbox Endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
