# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0-rc7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.void_invoice_action_create import VoidInvoiceActionCreate

class TestVoidInvoiceActionCreate(unittest.TestCase):
    """VoidInvoiceActionCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VoidInvoiceActionCreate:
        """Test VoidInvoiceActionCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VoidInvoiceActionCreate`
        """
        model = VoidInvoiceActionCreate()
        if include_optional:
            return VoidInvoiceActionCreate(
                percentage = 50,
                action = moolabs.models.void_invoice_line_action_create.VoidInvoiceLineActionCreate()
            )
        else:
            return VoidInvoiceActionCreate(
                percentage = 50,
                action = moolabs.models.void_invoice_line_action_create.VoidInvoiceLineActionCreate(),
        )
        """

    def testVoidInvoiceActionCreate(self):
        """Test VoidInvoiceActionCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
