# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0-rc1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.billing_profile_customer_override_create import BillingProfileCustomerOverrideCreate

class TestBillingProfileCustomerOverrideCreate(unittest.TestCase):
    """BillingProfileCustomerOverrideCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillingProfileCustomerOverrideCreate:
        """Test BillingProfileCustomerOverrideCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillingProfileCustomerOverrideCreate`
        """
        model = BillingProfileCustomerOverrideCreate()
        if include_optional:
            return BillingProfileCustomerOverrideCreate(
                billing_profile_id = '01G65Z755AFWAKHE12NY0CQ9FH'
            )
        else:
            return BillingProfileCustomerOverrideCreate(
        )
        """

    def testBillingProfileCustomerOverrideCreate(self):
        """Test BillingProfileCustomerOverrideCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
