# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0-rc3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.create_stripe_customer_portal_session_params import CreateStripeCustomerPortalSessionParams

class TestCreateStripeCustomerPortalSessionParams(unittest.TestCase):
    """CreateStripeCustomerPortalSessionParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateStripeCustomerPortalSessionParams:
        """Test CreateStripeCustomerPortalSessionParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateStripeCustomerPortalSessionParams`
        """
        model = CreateStripeCustomerPortalSessionParams()
        if include_optional:
            return CreateStripeCustomerPortalSessionParams(
                configuration_id = '',
                locale = '',
                return_url = ''
            )
        else:
            return CreateStripeCustomerPortalSessionParams(
        )
        """

    def testCreateStripeCustomerPortalSessionParams(self):
        """Test CreateStripeCustomerPortalSessionParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
