# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.connector_item import ConnectorItem

class TestConnectorItem(unittest.TestCase):
    """ConnectorItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConnectorItem:
        """Test ConnectorItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConnectorItem`
        """
        model = ConnectorItem()
        if include_optional:
            return ConnectorItem(
                id = '',
                name = '',
                category = '',
                status = '',
                auth_status = '',
                last_sync = '',
                mapping_info = '',
                sync_direction = '',
                owner = '',
                config = {
                    'key' : null
                    }
            )
        else:
            return ConnectorItem(
                id = '',
                name = '',
                category = '',
                status = '',
                auth_status = '',
                last_sync = '',
                config = {
                    'key' : null
                    },
        )
        """

    def testConnectorItem(self):
        """Test ConnectorItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
