# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0-rc3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.marketplace_listing import MarketplaceListing

class TestMarketplaceListing(unittest.TestCase):
    """MarketplaceListing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketplaceListing:
        """Test MarketplaceListing
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketplaceListing`
        """
        model = MarketplaceListing()
        if include_optional:
            return MarketplaceListing(
                type = 'stripe',
                name = '',
                description = '',
                capabilities = [
                    {type=collectPayments, key=stripe_collect_payment, name=Collect Payments, description=Stripe payments collects outstanding revenue with Stripe customer's default payment method.}
                    ],
                install_methods = [
                    'with_oauth2'
                    ]
            )
        else:
            return MarketplaceListing(
                type = 'stripe',
                name = '',
                description = '',
                capabilities = [
                    {type=collectPayments, key=stripe_collect_payment, name=Collect Payments, description=Stripe payments collects outstanding revenue with Stripe customer's default payment method.}
                    ],
                install_methods = [
                    'with_oauth2'
                    ],
        )
        """

    def testMarketplaceListing(self):
        """Test MarketplaceListing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
