# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0-rc7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.api.app_stripe_api import AppStripeApi


class TestAppStripeApi(unittest.TestCase):
    """AppStripeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AppStripeApi()

    def tearDown(self) -> None:
        pass

    def test_app_stripe_webhook(self) -> None:
        """Test case for app_stripe_webhook

        Stripe webhook
        """
        pass

    def test_create_stripe_checkout_session(self) -> None:
        """Test case for create_stripe_checkout_session

        Create checkout session
        """
        pass

    def test_update_stripe_api_key(self) -> None:
        """Test case for update_stripe_api_key

        Update Stripe API key
        """
        pass


if __name__ == '__main__':
    unittest.main()
