# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.overview_response import OverviewResponse

class TestOverviewResponse(unittest.TestCase):
    """OverviewResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OverviewResponse:
        """Test OverviewResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OverviewResponse`
        """
        model = OverviewResponse()
        if include_optional:
            return OverviewResponse(
                currency = '',
                total_spend = 1.337,
                requests = 56,
                reconciled_percent = 1.337,
                observation_status = '',
                ingest_health = moolabs.models.ingest_health.IngestHealth(
                    events_last_hour = 56, 
                    events_last_24h = 56, 
                    consumer_lag_estimate = 56, 
                    cache_hit_ratio = 1.337, 
                    dlq_count_24h = 56, 
                    status = '', )
            )
        else:
            return OverviewResponse(
                currency = '',
                total_spend = 1.337,
                requests = 56,
                reconciled_percent = 1.337,
                observation_status = '',
                ingest_health = moolabs.models.ingest_health.IngestHealth(
                    events_last_hour = 56, 
                    events_last_24h = 56, 
                    consumer_lag_estimate = 56, 
                    cache_hit_ratio = 1.337, 
                    dlq_count_24h = 56, 
                    status = '', ),
        )
        """

    def testOverviewResponse(self):
        """Test OverviewResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
