# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.marketplace_app_api_key_install_request import MarketplaceAppAPIKeyInstallRequest

class TestMarketplaceAppAPIKeyInstallRequest(unittest.TestCase):
    """MarketplaceAppAPIKeyInstallRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketplaceAppAPIKeyInstallRequest:
        """Test MarketplaceAppAPIKeyInstallRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketplaceAppAPIKeyInstallRequest`
        """
        model = MarketplaceAppAPIKeyInstallRequest()
        if include_optional:
            return MarketplaceAppAPIKeyInstallRequest(
                name = '',
                create_billing_profile = True,
                api_key = ''
            )
        else:
            return MarketplaceAppAPIKeyInstallRequest(
                api_key = '',
        )
        """

    def testMarketplaceAppAPIKeyInstallRequest(self):
        """Test MarketplaceAppAPIKeyInstallRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
