# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.invoice_available_action_details import InvoiceAvailableActionDetails

class TestInvoiceAvailableActionDetails(unittest.TestCase):
    """InvoiceAvailableActionDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceAvailableActionDetails:
        """Test InvoiceAvailableActionDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceAvailableActionDetails`
        """
        model = InvoiceAvailableActionDetails()
        if include_optional:
            return InvoiceAvailableActionDetails(
                resulting_state = ''
            )
        else:
            return InvoiceAvailableActionDetails(
                resulting_state = '',
        )
        """

    def testInvoiceAvailableActionDetails(self):
        """Test InvoiceAvailableActionDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
