# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.quote_response import QuoteResponse

class TestQuoteResponse(unittest.TestCase):
    """QuoteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuoteResponse:
        """Test QuoteResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuoteResponse`
        """
        model = QuoteResponse()
        if include_optional:
            return QuoteResponse(
                id = '',
                tenant_id = '',
                account_ref = {
                    'key' : null
                    },
                deal_ref = {
                    'key' : null
                    },
                buyer_contact_ref = {
                    'key' : null
                    },
                quote_type = 'new_subscription',
                owner_user_id = '',
                current_version = 56,
                state = '',
                expires_at = ''
            )
        else:
            return QuoteResponse(
                id = '',
                tenant_id = '',
                account_ref = {
                    'key' : null
                    },
                deal_ref = {
                    'key' : null
                    },
                buyer_contact_ref = {
                    'key' : null
                    },
                owner_user_id = '',
                current_version = 56,
                state = '',
        )
        """

    def testQuoteResponse(self):
        """Test QuoteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
