# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.lifecycle_event_request import LifecycleEventRequest

class TestLifecycleEventRequest(unittest.TestCase):
    """LifecycleEventRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LifecycleEventRequest:
        """Test LifecycleEventRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LifecycleEventRequest`
        """
        model = LifecycleEventRequest()
        if include_optional:
            return LifecycleEventRequest(
                subscription_id = '',
                event_type = '',
                event_id = '',
                effective_at = '',
                subscription_data = {
                    'key' : null
                    },
                payload_json = ''
            )
        else:
            return LifecycleEventRequest(
                subscription_id = '',
                event_type = '',
                event_id = '',
                effective_at = '',
        )
        """

    def testLifecycleEventRequest(self):
        """Test LifecycleEventRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
