# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc10
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.plan_addon_create import PlanAddonCreate

class TestPlanAddonCreate(unittest.TestCase):
    """PlanAddonCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlanAddonCreate:
        """Test PlanAddonCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlanAddonCreate`
        """
        model = PlanAddonCreate()
        if include_optional:
            return PlanAddonCreate(
                metadata = {externalId=019142cc-a016-796a-8113-1a942fecd26d},
                from_plan_phase = '',
                max_quantity = 56,
                addon_id = '01G65Z755AFWAKHE12NY0CQ9FH'
            )
        else:
            return PlanAddonCreate(
                from_plan_phase = '',
                addon_id = '01G65Z755AFWAKHE12NY0CQ9FH',
        )
        """

    def testPlanAddonCreate(self):
        """Test PlanAddonCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
