# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.payment_item import PaymentItem

class TestPaymentItem(unittest.TestCase):
    """PaymentItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentItem:
        """Test PaymentItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentItem`
        """
        model = PaymentItem()
        if include_optional:
            return PaymentItem(
                id = '',
                netsuite_id = '',
                customer_internal_id = '',
                payment_amount = '',
                applied_invoice_id = '',
                applied_amount = '',
                tran_date = '',
                ns_last_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                synced_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return PaymentItem(
                id = '',
                netsuite_id = '',
                customer_internal_id = '',
                applied_invoice_id = '',
        )
        """

    def testPaymentItem(self):
        """Test PaymentItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
