# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.promise_response import PromiseResponse

class TestPromiseResponse(unittest.TestCase):
    """PromiseResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromiseResponse:
        """Test PromiseResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromiseResponse`
        """
        model = PromiseResponse()
        if include_optional:
            return PromiseResponse(
                id = '',
                case_id = '',
                invoice_id = '',
                promised_amount_micros = 56,
                fulfilled_amount_micros = 56,
                currency_code = '',
                promised_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                status = '',
                broken_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                captured_from_channel = '',
                captured_by = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return PromiseResponse(
                id = '',
                case_id = '',
                promised_amount_micros = 56,
                currency_code = '',
                promised_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                status = '',
                captured_from_channel = '',
                captured_by = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testPromiseResponse(self):
        """Test PromiseResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
