# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.api.meters_api import MetersApi


class TestMetersApi(unittest.TestCase):
    """MetersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetersApi()

    def tearDown(self) -> None:
        pass

    def test_create_meter(self) -> None:
        """Test case for create_meter

        Create meter
        """
        pass

    def test_delete_meter(self) -> None:
        """Test case for delete_meter

        Delete meter
        """
        pass

    def test_get_meter(self) -> None:
        """Test case for get_meter

        Get meter
        """
        pass

    def test_get_usage_summary(self) -> None:
        """Test case for get_usage_summary

        Get multi-meter usage summary
        """
        pass

    def test_list_meter_group_by_values(self) -> None:
        """Test case for list_meter_group_by_values

        List meter group by values
        """
        pass

    def test_list_meter_subjects(self) -> None:
        """Test case for list_meter_subjects

        List meter subjects
        """
        pass

    def test_list_meters(self) -> None:
        """Test case for list_meters

        List meters
        """
        pass

    def test_query_meter(self) -> None:
        """Test case for query_meter

        Query meter
        """
        pass

    def test_query_meter_post(self) -> None:
        """Test case for query_meter_post

        Query meter
        """
        pass

    def test_test_meter_event(self) -> None:
        """Test case for test_meter_event

        Validate a sample event payload against the meter
        """
        pass

    def test_update_meter(self) -> None:
        """Test case for update_meter

        Update meter
        """
        pass


if __name__ == '__main__':
    unittest.main()
