# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.notification_event import NotificationEvent

class TestNotificationEvent(unittest.TestCase):
    """NotificationEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotificationEvent:
        """Test NotificationEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotificationEvent`
        """
        model = NotificationEvent()
        if include_optional:
            return NotificationEvent(
                id = '01J2KNP1YTXQRXHTDJ4KPR7PZ0',
                type = 'entitlements.balance.threshold',
                created_at = '2023-01-01T01:01:01.001Z',
                rule = moolabs.models.notification_rule.NotificationRule(),
                delivery_status = [
                    moolabs.models.notification_event_delivery_status.NotificationEventDeliveryStatus(
                        state = SUCCESS, 
                        reason = 'Failed to dispatch event due to provider error.', 
                        updated_at = '2023-01-01T01:01:01.001Z', 
                        channel = null, 
                        annotations = null, 
                        next_attempt = '2023-01-01T01:01:01.001Z', 
                        attempts = [
                            moolabs.models.notification_event_delivery_attempt.NotificationEventDeliveryAttempt(
                                state = SUCCESS, 
                                response = null, 
                                timestamp = '2023-01-01T01:01:01.001Z', )
                            ], )
                    ],
                payload = moolabs.models.notification_event_payload.NotificationEventPayload(),
                annotations = {externalId=019142cc-a016-796a-8113-1a942fecd26d}
            )
        else:
            return NotificationEvent(
                id = '01J2KNP1YTXQRXHTDJ4KPR7PZ0',
                type = 'entitlements.balance.threshold',
                created_at = '2023-01-01T01:01:01.001Z',
                rule = moolabs.models.notification_rule.NotificationRule(),
                delivery_status = [
                    moolabs.models.notification_event_delivery_status.NotificationEventDeliveryStatus(
                        state = SUCCESS, 
                        reason = 'Failed to dispatch event due to provider error.', 
                        updated_at = '2023-01-01T01:01:01.001Z', 
                        channel = null, 
                        annotations = null, 
                        next_attempt = '2023-01-01T01:01:01.001Z', 
                        attempts = [
                            moolabs.models.notification_event_delivery_attempt.NotificationEventDeliveryAttempt(
                                state = SUCCESS, 
                                response = null, 
                                timestamp = '2023-01-01T01:01:01.001Z', )
                            ], )
                    ],
                payload = moolabs.models.notification_event_payload.NotificationEventPayload(),
        )
        """

    def testNotificationEvent(self):
        """Test NotificationEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
