# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.reconciliation_basis_out import ReconciliationBasisOut

class TestReconciliationBasisOut(unittest.TestCase):
    """ReconciliationBasisOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReconciliationBasisOut:
        """Test ReconciliationBasisOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReconciliationBasisOut`
        """
        model = ReconciliationBasisOut()
        if include_optional:
            return ReconciliationBasisOut(
                grade = '',
                data_freshness = '',
                cost_completeness_pct = 1.337,
                observation_status = '',
                bom_approved_at = ''
            )
        else:
            return ReconciliationBasisOut(
                grade = '',
                data_freshness = '',
                cost_completeness_pct = 1.337,
                observation_status = '',
                bom_approved_at = '',
        )
        """

    def testReconciliationBasisOut(self):
        """Test ReconciliationBasisOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
