# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.variance_decomposition_out import VarianceDecompositionOut

class TestVarianceDecompositionOut(unittest.TestCase):
    """VarianceDecompositionOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VarianceDecompositionOut:
        """Test VarianceDecompositionOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VarianceDecompositionOut`
        """
        model = VarianceDecompositionOut()
        if include_optional:
            return VarianceDecompositionOut(
                feature_key = '',
                period_start = '',
                period_end = '',
                standard_cost = 1.337,
                actual_cost = 1.337,
                total_variance = 1.337,
                price_variance = 1.337,
                usage_variance = 1.337,
                volume_variance = 1.337,
                mix_variance = 1.337,
                attribution_tier = '',
                heuristic_alert = True,
                bom_version = 56,
                bom_template_id = '',
                computed_at = '',
                alert_note = ''
            )
        else:
            return VarianceDecompositionOut(
                feature_key = '',
                period_start = '',
                period_end = '',
                standard_cost = 1.337,
                actual_cost = 1.337,
                total_variance = 1.337,
                price_variance = 1.337,
                usage_variance = 1.337,
                volume_variance = 1.337,
                mix_variance = 1.337,
                attribution_tier = '',
                heuristic_alert = True,
                bom_version = 56,
                bom_template_id = '',
                computed_at = '',
        )
        """

    def testVarianceDecompositionOut(self):
        """Test VarianceDecompositionOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
