# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.sdk_span import SDKSpan

class TestSDKSpan(unittest.TestCase):
    """SDKSpan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SDKSpan:
        """Test SDKSpan
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SDKSpan`
        """
        model = SDKSpan()
        if include_optional:
            return SDKSpan(
                span_id = '0',
                provider = '0',
                model = '0',
                operation_type = '0',
                input_tokens = 0.0,
                output_tokens = 0.0,
                tool_calls = 0.0,
                latency_ms = 0.0,
                cache_hit = True,
                metadata = {
                    'key' : null
                    }
            )
        else:
            return SDKSpan(
                span_id = '0',
                provider = '0',
                model = '0',
                operation_type = '0',
        )
        """

    def testSDKSpan(self):
        """Test SDKSpan"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
