# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.create_fx_rate_request import CreateFxRateRequest

class TestCreateFxRateRequest(unittest.TestCase):
    """CreateFxRateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateFxRateRequest:
        """Test CreateFxRateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateFxRateRequest`
        """
        model = CreateFxRateRequest()
        if include_optional:
            return CreateFxRateRequest(
                tenant_id = '',
                pool_id = '',
                credits_per_usd_micros = 56,
                effective_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                rate_version = '',
                usd_micros = 0.0,
                created_by = ''
            )
        else:
            return CreateFxRateRequest(
                tenant_id = '',
                pool_id = '',
                credits_per_usd_micros = 56,
                effective_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testCreateFxRateRequest(self):
        """Test CreateFxRateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
