# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.evidence_response import EvidenceResponse

class TestEvidenceResponse(unittest.TestCase):
    """EvidenceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EvidenceResponse:
        """Test EvidenceResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EvidenceResponse`
        """
        model = EvidenceResponse()
        if include_optional:
            return EvidenceResponse(
                id = '',
                dispute_id = '',
                evidence_type = '',
                source_table = '',
                source_id = '',
                summary = '',
                amount_micros = 56,
                resolved_amount_micros = 56,
                resolution_status = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return EvidenceResponse(
                id = '',
                dispute_id = '',
                source_table = '',
                source_id = '',
        )
        """

    def testEvidenceResponse(self):
        """Test EvidenceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
