# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.1.0-rc1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.meter_update import MeterUpdate

class TestMeterUpdate(unittest.TestCase):
    """MeterUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MeterUpdate:
        """Test MeterUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MeterUpdate`
        """
        model = MeterUpdate()
        if include_optional:
            return MeterUpdate(
                description = '',
                metadata = {externalId=019142cc-a016-796a-8113-1a942fecd26d},
                name = '0',
                group_by = {type=$.type}
            )
        else:
            return MeterUpdate(
        )
        """

    def testMeterUpdate(self):
        """Test MeterUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
