# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0-rc7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.addon_replace_update import AddonReplaceUpdate

class TestAddonReplaceUpdate(unittest.TestCase):
    """AddonReplaceUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddonReplaceUpdate:
        """Test AddonReplaceUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddonReplaceUpdate`
        """
        model = AddonReplaceUpdate()
        if include_optional:
            return AddonReplaceUpdate(
                name = '0',
                description = '',
                metadata = {externalId=019142cc-a016-796a-8113-1a942fecd26d},
                instance_type = 'single',
                rate_cards = [
                    moolabs.models.rate_card.RateCard()
                    ]
            )
        else:
            return AddonReplaceUpdate(
                name = '0',
                instance_type = 'single',
                rate_cards = [
                    moolabs.models.rate_card.RateCard()
                    ],
        )
        """

    def testAddonReplaceUpdate(self):
        """Test AddonReplaceUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
