# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.notification_channel_webhook import NotificationChannelWebhook

class TestNotificationChannelWebhook(unittest.TestCase):
    """NotificationChannelWebhook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotificationChannelWebhook:
        """Test NotificationChannelWebhook
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotificationChannelWebhook`
        """
        model = NotificationChannelWebhook()
        if include_optional:
            return NotificationChannelWebhook(
                created_at = '2024-01-01T01:01:01.001Z',
                updated_at = '2024-01-01T01:01:01.001Z',
                deleted_at = '2024-01-01T01:01:01.001Z',
                id = '01ARZ3NDEKTSV4RRFFQ69G5FAV',
                type = 'WEBHOOK',
                name = 'customer-webhook',
                disabled = True,
                annotations = {externalId=019142cc-a016-796a-8113-1a942fecd26d},
                metadata = {externalId=019142cc-a016-796a-8113-1a942fecd26d},
                url = 'https://example.com/webhook',
                custom_headers = {
                    'key' : ''
                    },
                signing_secret = 'whsec_S6g2HLnTwd9AhHwUIMFggVS9OfoPafN8'
            )
        else:
            return NotificationChannelWebhook(
                created_at = '2024-01-01T01:01:01.001Z',
                updated_at = '2024-01-01T01:01:01.001Z',
                id = '01ARZ3NDEKTSV4RRFFQ69G5FAV',
                type = 'WEBHOOK',
                name = 'customer-webhook',
                url = 'https://example.com/webhook',
        )
        """

    def testNotificationChannelWebhook(self):
        """Test NotificationChannelWebhook"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
