# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.1.0-rc1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.price import Price

class TestPrice(unittest.TestCase):
    """Price unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Price:
        """Test Price
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Price`
        """
        model = Price()
        if include_optional:
            return Price(
                type = 'flat',
                amount = '-80728',
                mode = 'volume',
                tiers = [
                    moolabs.models.price_tier.PriceTier(
                        up_to_amount = null, 
                        flat_price = moolabs.models.flat_price_component.Flat price component(), 
                        unit_price = moolabs.models.unit_price_component.Unit price component(), )
                    ],
                multiplier = '-80728',
                quantity_per_package = '-80728'
            )
        else:
            return Price(
                type = 'flat',
                amount = '-80728',
                mode = 'volume',
                tiers = [
                    moolabs.models.price_tier.PriceTier(
                        up_to_amount = null, 
                        flat_price = moolabs.models.flat_price_component.Flat price component(), 
                        unit_price = moolabs.models.unit_price_component.Unit price component(), )
                    ],
                quantity_per_package = '-80728',
        )
        """

    def testPrice(self):
        """Test Price"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
