# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.line_item_create import LineItemCreate

class TestLineItemCreate(unittest.TestCase):
    """LineItemCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LineItemCreate:
        """Test LineItemCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LineItemCreate`
        """
        model = LineItemCreate()
        if include_optional:
            return LineItemCreate(
                metric_type = '',
                quantity = None,
                unit = '',
                rate_snapshot_id = '',
                unit_cost = None,
                line_total = None,
                reporting_line_total = None,
                metadata = {
                    'key' : null
                    }
            )
        else:
            return LineItemCreate(
                metric_type = '',
                quantity = None,
                unit = '',
                unit_cost = None,
                line_total = None,
                reporting_line_total = None,
        )
        """

    def testLineItemCreate(self):
        """Test LineItemCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
