# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.auto_topup_activity_response import AutoTopupActivityResponse

class TestAutoTopupActivityResponse(unittest.TestCase):
    """AutoTopupActivityResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AutoTopupActivityResponse:
        """Test AutoTopupActivityResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AutoTopupActivityResponse`
        """
        model = AutoTopupActivityResponse()
        if include_optional:
            return AutoTopupActivityResponse(
                items = [
                    moolabs.models.auto_topup_activity_item.AutoTopupActivityItem(
                        id = '', 
                        rule_id = '', 
                        wallet_id = '', 
                        triggered_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        triggered_balance_micros = 56, 
                        topup_amount_micros = 56, 
                        status = '', 
                        reference_id = '', 
                        error_message = '', )
                    ],
                total = 56
            )
        else:
            return AutoTopupActivityResponse(
                items = [
                    moolabs.models.auto_topup_activity_item.AutoTopupActivityItem(
                        id = '', 
                        rule_id = '', 
                        wallet_id = '', 
                        triggered_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        triggered_balance_micros = 56, 
                        topup_amount_micros = 56, 
                        status = '', 
                        reference_id = '', 
                        error_message = '', )
                    ],
                total = 56,
        )
        """

    def testAutoTopupActivityResponse(self):
        """Test AutoTopupActivityResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
