# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0-rc2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.price_tier import PriceTier

class TestPriceTier(unittest.TestCase):
    """PriceTier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PriceTier:
        """Test PriceTier
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PriceTier`
        """
        model = PriceTier()
        if include_optional:
            return PriceTier(
                up_to_amount = '-80728',
                flat_price = moolabs.models.flat_price.FlatPrice(
                    type = 'flat', 
                    amount = null, ),
                unit_price = moolabs.models.unit_price.UnitPrice(
                    type = 'unit', 
                    amount = null, )
            )
        else:
            return PriceTier(
                flat_price = moolabs.models.flat_price.FlatPrice(
                    type = 'flat', 
                    amount = null, ),
                unit_price = moolabs.models.unit_price.UnitPrice(
                    type = 'unit', 
                    amount = null, ),
        )
        """

    def testPriceTier(self):
        """Test PriceTier"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
