# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0-rc6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.entitlement_create_shared_fields import EntitlementCreateSharedFields

class TestEntitlementCreateSharedFields(unittest.TestCase):
    """EntitlementCreateSharedFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntitlementCreateSharedFields:
        """Test EntitlementCreateSharedFields
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntitlementCreateSharedFields`
        """
        model = EntitlementCreateSharedFields()
        if include_optional:
            return EntitlementCreateSharedFields(
                feature_key = 'example-feature-key',
                feature_id = '01ARZ3NDEKTSV4RRFFQ69G5FAV',
                metadata = {externalId=019142cc-a016-796a-8113-1a942fecd26d},
                usage_period = {interval=DAY, anchor=2023-01-01T01:01:01.001Z}
            )
        else:
            return EntitlementCreateSharedFields(
        )
        """

    def testEntitlementCreateSharedFields(self):
        """Test EntitlementCreateSharedFields"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
