# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.create_stripe_checkout_session_request_options import CreateStripeCheckoutSessionRequestOptions

class TestCreateStripeCheckoutSessionRequestOptions(unittest.TestCase):
    """CreateStripeCheckoutSessionRequestOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateStripeCheckoutSessionRequestOptions:
        """Test CreateStripeCheckoutSessionRequestOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateStripeCheckoutSessionRequestOptions`
        """
        model = CreateStripeCheckoutSessionRequestOptions()
        if include_optional:
            return CreateStripeCheckoutSessionRequestOptions(
                billing_address_collection = 'auto',
                cancel_url = '',
                client_reference_id = '',
                customer_update = moolabs.models.create_stripe_checkout_session_customer_update.CreateStripeCheckoutSessionCustomerUpdate(
                    address = null, 
                    name = null, 
                    shipping = null, ),
                consent_collection = moolabs.models.create_stripe_checkout_session_consent_collection.CreateStripeCheckoutSessionConsentCollection(
                    payment_method_reuse_agreement = null, 
                    promotions = null, 
                    terms_of_service = null, ),
                currency = 'USD',
                custom_text = moolabs.models.checkout_session_custom_text_after_submit_params.CheckoutSessionCustomTextAfterSubmitParams(
                    after_submit = moolabs.models.checkout_session_custom_text_after_submit_params_after_submit.CheckoutSessionCustomTextAfterSubmitParams_afterSubmit(
                        message = '', ), 
                    shipping_address = moolabs.models.checkout_session_custom_text_after_submit_params_shipping_address.CheckoutSessionCustomTextAfterSubmitParams_shippingAddress(
                        message = '', ), 
                    submit = moolabs.models.checkout_session_custom_text_after_submit_params_submit.CheckoutSessionCustomTextAfterSubmitParams_submit(
                        message = '', ), 
                    terms_of_service_acceptance = moolabs.models.checkout_session_custom_text_after_submit_params_terms_of_service_acceptance.CheckoutSessionCustomTextAfterSubmitParams_termsOfServiceAcceptance(
                        message = '', ), ),
                expires_at = 56,
                locale = '',
                metadata = {
                    'key' : ''
                    },
                return_url = '',
                success_url = '',
                ui_mode = 'embedded',
                payment_method_types = [
                    ''
                    ],
                redirect_on_completion = 'always',
                tax_id_collection = moolabs.models.create_checkout_session_tax_id_collection.CreateCheckoutSessionTaxIdCollection(
                    enabled = True, 
                    required = null, )
            )
        else:
            return CreateStripeCheckoutSessionRequestOptions(
        )
        """

    def testCreateStripeCheckoutSessionRequestOptions(self):
        """Test CreateStripeCheckoutSessionRequestOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
