# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0-rc7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.api.app_custom_invoicing_api import AppCustomInvoicingApi


class TestAppCustomInvoicingApi(unittest.TestCase):
    """AppCustomInvoicingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AppCustomInvoicingApi()

    def tearDown(self) -> None:
        pass

    def test_app_custom_invoicing_draft_synchronized(self) -> None:
        """Test case for app_custom_invoicing_draft_synchronized

        Submit draft synchronization results
        """
        pass

    def test_app_custom_invoicing_issuing_synchronized(self) -> None:
        """Test case for app_custom_invoicing_issuing_synchronized

        Submit issuing synchronization results
        """
        pass

    def test_app_custom_invoicing_update_payment_status(self) -> None:
        """Test case for app_custom_invoicing_update_payment_status

        Update payment status
        """
        pass


if __name__ == '__main__':
    unittest.main()
