# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc8
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.edit_subscription_remove_item import EditSubscriptionRemoveItem

class TestEditSubscriptionRemoveItem(unittest.TestCase):
    """EditSubscriptionRemoveItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EditSubscriptionRemoveItem:
        """Test EditSubscriptionRemoveItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EditSubscriptionRemoveItem`
        """
        model = EditSubscriptionRemoveItem()
        if include_optional:
            return EditSubscriptionRemoveItem(
                op = 'remove_item',
                phase_key = '',
                item_key = ''
            )
        else:
            return EditSubscriptionRemoveItem(
                op = 'remove_item',
                phase_key = '',
                item_key = '',
        )
        """

    def testEditSubscriptionRemoveItem(self):
        """Test EditSubscriptionRemoveItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
