# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.billing_profile_paginated_response import BillingProfilePaginatedResponse

class TestBillingProfilePaginatedResponse(unittest.TestCase):
    """BillingProfilePaginatedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillingProfilePaginatedResponse:
        """Test BillingProfilePaginatedResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillingProfilePaginatedResponse`
        """
        model = BillingProfilePaginatedResponse()
        if include_optional:
            return BillingProfilePaginatedResponse(
                total_count = 500,
                page = 1,
                page_size = 100,
                items = [
                    moolabs.models.billing_profile.BillingProfile(
                        id = '01G65Z755AFWAKHE12NY0CQ9FH', 
                        name = '0', 
                        description = '', 
                        metadata = moolabs.models.metadata.Metadata(), 
                        created_at = '2024-01-01T01:01:01.001Z', 
                        updated_at = '2024-01-01T01:01:01.001Z', 
                        deleted_at = '2024-01-01T01:01:01.001Z', 
                        supplier = null, 
                        workflow = null, 
                        apps = null, 
                        default = True, )
                    ]
            )
        else:
            return BillingProfilePaginatedResponse(
                total_count = 500,
                page = 1,
                page_size = 100,
                items = [
                    moolabs.models.billing_profile.BillingProfile(
                        id = '01G65Z755AFWAKHE12NY0CQ9FH', 
                        name = '0', 
                        description = '', 
                        metadata = moolabs.models.metadata.Metadata(), 
                        created_at = '2024-01-01T01:01:01.001Z', 
                        updated_at = '2024-01-01T01:01:01.001Z', 
                        deleted_at = '2024-01-01T01:01:01.001Z', 
                        supplier = null, 
                        workflow = null, 
                        apps = null, 
                        default = True, )
                    ],
        )
        """

    def testBillingProfilePaginatedResponse(self):
        """Test BillingProfilePaginatedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
