# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.notification_channel_type import NotificationChannelType

class TestNotificationChannelType(unittest.TestCase):
    """NotificationChannelType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotificationChannelType(self):
        """Test NotificationChannelType"""
        # inst = NotificationChannelType()

if __name__ == '__main__':
    unittest.main()
