# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.commercial_overrides_input import CommercialOverridesInput

class TestCommercialOverridesInput(unittest.TestCase):
    """CommercialOverridesInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommercialOverridesInput:
        """Test CommercialOverridesInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommercialOverridesInput`
        """
        model = CommercialOverridesInput()
        if include_optional:
            return CommercialOverridesInput(
                subscription_id = '',
                customer_id = '',
                tenant_id = '',
                effective_from = '',
                entitlement_overrides = [
                    moolabs.models.entitlement_override_input.EntitlementOverrideInput(
                        feature_key = '', 
                        entitlement_type = 'metered', 
                        default_value = '', 
                        override_value = '', 
                        window = 'Monthly', )
                    ],
                credit_override = moolabs.models.credit_override_input.CreditOverrideInput(
                    mode = '', 
                    amount = 1.337, 
                    unit = 'credits', 
                    expiry = '', 
                    start_date = '', 
                    end_date = '', 
                    note = '', 
                    pool_overrides = {
                        'key' : 1.337
                        }, ),
                rate_card_discount = moolabs.models.rate_card_discount_input.RateCardDiscountInput(
                    type = 'percentage', 
                    value = 1.337, 
                    scope = 'all', 
                    duration = 'entire', 
                    cycles = 56, 
                    start_date = '', 
                    end_date = '', 
                    selected_items = [
                        ''
                        ], 
                    note = '', )
            )
        else:
            return CommercialOverridesInput(
                subscription_id = '',
                customer_id = '',
                effective_from = '',
        )
        """

    def testCommercialOverridesInput(self):
        """Test CommercialOverridesInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
