# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0-rc7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.grant_order_by import GrantOrderBy

class TestGrantOrderBy(unittest.TestCase):
    """GrantOrderBy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGrantOrderBy(self):
        """Test GrantOrderBy"""
        # inst = GrantOrderBy()

if __name__ == '__main__':
    unittest.main()
