# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.api.promises_api import PromisesApi


class TestPromisesApi(unittest.TestCase):
    """PromisesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PromisesApi()

    def tearDown(self) -> None:
        pass

    def test_approve_ptp_endpoint(self) -> None:
        """Test case for approve_ptp_endpoint

        Approve Ptp Endpoint
        """
        pass

    def test_break_ptp_endpoint_v1_arc(self) -> None:
        """Test case for break_ptp_endpoint_v1_arc

        Break Ptp Endpoint
        """
        pass

    def test_cancel_ptp_endpoint_v1_arc(self) -> None:
        """Test case for cancel_ptp_endpoint_v1_arc

        Cancel Ptp Endpoint
        """
        pass

    def test_create_ptp_endpoint_v1_arc(self) -> None:
        """Test case for create_ptp_endpoint_v1_arc

        Create Ptp Endpoint
        """
        pass

    def test_create_ptp_payment_link_endpoint_v1_arc_cases(self) -> None:
        """Test case for create_ptp_payment_link_endpoint_v1_arc_cases

        Create Ptp Payment Link Endpoint
        """
        pass

    def test_fulfill_ptp_endpoint_v1_arc(self) -> None:
        """Test case for fulfill_ptp_endpoint_v1_arc

        Fulfill Ptp Endpoint
        """
        pass

    def test_list_ptps_endpoint_v1_arc(self) -> None:
        """Test case for list_ptps_endpoint_v1_arc

        List Ptps Endpoint
        """
        pass

    def test_reject_ptp_endpoint(self) -> None:
        """Test case for reject_ptp_endpoint

        Reject Ptp Endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
