# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.issue_after_reset import IssueAfterReset

class TestIssueAfterReset(unittest.TestCase):
    """IssueAfterReset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IssueAfterReset:
        """Test IssueAfterReset
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IssueAfterReset`
        """
        model = IssueAfterReset()
        if include_optional:
            return IssueAfterReset(
                amount = 0,
                priority = 1
            )
        else:
            return IssueAfterReset(
                amount = 0,
        )
        """

    def testIssueAfterReset(self):
        """Test IssueAfterReset"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
