# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0-rc2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.billing_workflow_collection_alignment_anchored import BillingWorkflowCollectionAlignmentAnchored

class TestBillingWorkflowCollectionAlignmentAnchored(unittest.TestCase):
    """BillingWorkflowCollectionAlignmentAnchored unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillingWorkflowCollectionAlignmentAnchored:
        """Test BillingWorkflowCollectionAlignmentAnchored
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillingWorkflowCollectionAlignmentAnchored`
        """
        model = BillingWorkflowCollectionAlignmentAnchored()
        if include_optional:
            return BillingWorkflowCollectionAlignmentAnchored(
                type = 'anchored',
                recurring_period = moolabs.models.recurring_period_v2.RecurringPeriodV2(
                    interval = null, 
                    anchor = '2023-01-01T01:01:01.001Z', )
            )
        else:
            return BillingWorkflowCollectionAlignmentAnchored(
                type = 'anchored',
                recurring_period = moolabs.models.recurring_period_v2.RecurringPeriodV2(
                    interval = null, 
                    anchor = '2023-01-01T01:01:01.001Z', ),
        )
        """

    def testBillingWorkflowCollectionAlignmentAnchored(self):
        """Test BillingWorkflowCollectionAlignmentAnchored"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
