# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.2.0-rc1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.grant_source_type import GrantSourceType

class TestGrantSourceType(unittest.TestCase):
    """GrantSourceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGrantSourceType(self):
        """Test GrantSourceType"""
        # inst = GrantSourceType()

if __name__ == '__main__':
    unittest.main()
