# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.api.admin_api import AdminApi


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminApi()

    def tearDown(self) -> None:
        pass

    def test_diagnose_subscription(self) -> None:
        """Test case for diagnose_subscription

        Diagnose Subscription
        """
        pass

    def test_get_ingest_dead_letter_endpoint_v1(self) -> None:
        """Test case for get_ingest_dead_letter_endpoint_v1

        Get Ingest Dead Letter Endpoint
        """
        pass

    def test_get_ingest_dead_letters_v1(self) -> None:
        """Test case for get_ingest_dead_letters_v1

        Get Ingest Dead Letters
        """
        pass

    def test_get_ledger_audit_get(self) -> None:
        """Test case for get_ledger_audit_get

        Get Ledger Audit
        """
        pass

    def test_get_ledger_balance_get(self) -> None:
        """Test case for get_ledger_balance_get

        Get Ledger Balance
        """
        pass

    def test_override_first_ingress_endpoint_v1(self) -> None:
        """Test case for override_first_ingress_endpoint_v1

        Override First Ingress Endpoint
        """
        pass

    def test_process_lifecycle_event_manually_v1_admin(self) -> None:
        """Test case for process_lifecycle_event_manually_v1_admin

        Process Lifecycle Event Manually
        """
        pass

    def test_replay_ingest_dead_letter_endpoint_v1(self) -> None:
        """Test case for replay_ingest_dead_letter_endpoint_v1

        Replay Ingest Dead Letter Endpoint
        """
        pass

    def test_retry_unpriced(self) -> None:
        """Test case for retry_unpriced

        Retry Unpriced
        """
        pass

    def test_review_quarantined(self) -> None:
        """Test case for review_quarantined

        Review Quarantined
        """
        pass

    def test_trigger_subscription_sync(self) -> None:
        """Test case for trigger_subscription_sync

        Trigger Subscription Sync
        """
        pass


if __name__ == '__main__':
    unittest.main()
