# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc10
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.api.subscription_overrides_api import SubscriptionOverridesApi


class TestSubscriptionOverridesApi(unittest.TestCase):
    """SubscriptionOverridesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionOverridesApi()

    def tearDown(self) -> None:
        pass

    def test_create_commercial_overrides_v1(self) -> None:
        """Test case for create_commercial_overrides_v1

        Create Commercial Overrides
        """
        pass

    def test_get_commercial_overrides_v1(self) -> None:
        """Test case for get_commercial_overrides_v1

        Get Commercial Overrides
        """
        pass


if __name__ == '__main__':
    unittest.main()
