# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0-rc7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.grant_paginated_response import GrantPaginatedResponse

class TestGrantPaginatedResponse(unittest.TestCase):
    """GrantPaginatedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GrantPaginatedResponse:
        """Test GrantPaginatedResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GrantPaginatedResponse`
        """
        model = GrantPaginatedResponse()
        if include_optional:
            return GrantPaginatedResponse(
                total_count = 500,
                page = 1,
                page_size = 100,
                items = [
                    moolabs.models.entitlement_grant.EntitlementGrant(
                        created_at = '2024-01-01T01:01:01.001Z', 
                        updated_at = '2024-01-01T01:01:01.001Z', 
                        deleted_at = '2024-01-01T01:01:01.001Z', 
                        amount = 100, 
                        priority = 1, 
                        effective_at = '2023-01-01T01:01:01.001Z', 
                        expiration = null, 
                        max_rollover_amount = 100, 
                        min_rollover_amount = 100, 
                        metadata = {stripePaymentId=pi_4OrAkhLvyihio9p51h9iiFnB}, 
                        id = '01ARZ3NDEKTSV4RRFFQ69G5FAV', 
                        entitlement_id = '01ARZ3NDEKTSV4RRFFQ69G5FAV', 
                        next_recurrence = '2023-01-01T01:01:01.001Z', 
                        expires_at = '2023-01-01T01:01:01.001Z', 
                        voided_at = '2023-01-01T01:01:01.001Z', 
                        recurrence = null, 
                        annotations = {issueAfterReset=true}, )
                    ]
            )
        else:
            return GrantPaginatedResponse(
                total_count = 500,
                page = 1,
                page_size = 100,
                items = [
                    moolabs.models.entitlement_grant.EntitlementGrant(
                        created_at = '2024-01-01T01:01:01.001Z', 
                        updated_at = '2024-01-01T01:01:01.001Z', 
                        deleted_at = '2024-01-01T01:01:01.001Z', 
                        amount = 100, 
                        priority = 1, 
                        effective_at = '2023-01-01T01:01:01.001Z', 
                        expiration = null, 
                        max_rollover_amount = 100, 
                        min_rollover_amount = 100, 
                        metadata = {stripePaymentId=pi_4OrAkhLvyihio9p51h9iiFnB}, 
                        id = '01ARZ3NDEKTSV4RRFFQ69G5FAV', 
                        entitlement_id = '01ARZ3NDEKTSV4RRFFQ69G5FAV', 
                        next_recurrence = '2023-01-01T01:01:01.001Z', 
                        expires_at = '2023-01-01T01:01:01.001Z', 
                        voided_at = '2023-01-01T01:01:01.001Z', 
                        recurrence = null, 
                        annotations = {issueAfterReset=true}, )
                    ],
        )
        """

    def testGrantPaginatedResponse(self):
        """Test GrantPaginatedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
