# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.invoice_detailed_line_rate_card import InvoiceDetailedLineRateCard

class TestInvoiceDetailedLineRateCard(unittest.TestCase):
    """InvoiceDetailedLineRateCard unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceDetailedLineRateCard:
        """Test InvoiceDetailedLineRateCard
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceDetailedLineRateCard`
        """
        model = InvoiceDetailedLineRateCard()
        if include_optional:
            return InvoiceDetailedLineRateCard(
                tax_config = moolabs.models.tax_config.TaxConfig(
                    behavior = null, 
                    stripe = null, 
                    custom_invoicing = null, ),
                price = moolabs.models.flat_price_with_payment_term.FlatPriceWithPaymentTerm(
                    type = 'flat', 
                    amount = null, 
                    payment_term = null, ),
                quantity = '-80728',
                discounts = moolabs.models.billing_discounts.BillingDiscounts(
                    percentage = null, 
                    usage = null, )
            )
        else:
            return InvoiceDetailedLineRateCard(
                price = moolabs.models.flat_price_with_payment_term.FlatPriceWithPaymentTerm(
                    type = 'flat', 
                    amount = null, 
                    payment_term = null, ),
        )
        """

    def testInvoiceDetailedLineRateCard(self):
        """Test InvoiceDetailedLineRateCard"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
