# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.expiration_duration import ExpirationDuration

class TestExpirationDuration(unittest.TestCase):
    """ExpirationDuration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExpirationDuration(self):
        """Test ExpirationDuration"""
        # inst = ExpirationDuration()

if __name__ == '__main__':
    unittest.main()
