# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0-rc4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.marketplace_install_response import MarketplaceInstallResponse

class TestMarketplaceInstallResponse(unittest.TestCase):
    """MarketplaceInstallResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketplaceInstallResponse:
        """Test MarketplaceInstallResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketplaceInstallResponse`
        """
        model = MarketplaceInstallResponse()
        if include_optional:
            return MarketplaceInstallResponse(
                app = moolabs.models.app.App(),
                default_for_capability_types = [
                    'reportUsage'
                    ]
            )
        else:
            return MarketplaceInstallResponse(
                app = moolabs.models.app.App(),
                default_for_capability_types = [
                    'reportUsage'
                    ],
        )
        """

    def testMarketplaceInstallResponse(self):
        """Test MarketplaceInstallResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
