# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.entitlement_override_input import EntitlementOverrideInput

class TestEntitlementOverrideInput(unittest.TestCase):
    """EntitlementOverrideInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntitlementOverrideInput:
        """Test EntitlementOverrideInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntitlementOverrideInput`
        """
        model = EntitlementOverrideInput()
        if include_optional:
            return EntitlementOverrideInput(
                feature_key = '',
                entitlement_type = 'metered',
                default_value = '',
                override_value = '',
                window = 'Monthly'
            )
        else:
            return EntitlementOverrideInput(
                feature_key = '',
                override_value = '',
        )
        """

    def testEntitlementOverrideInput(self):
        """Test EntitlementOverrideInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
