# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.api.contract_editor_api import ContractEditorApi


class TestContractEditorApi(unittest.TestCase):
    """ContractEditorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContractEditorApi()

    def tearDown(self) -> None:
        pass

    def test_ai_redline_contract_v1(self) -> None:
        """Test case for ai_redline_contract_v1

        Ai Redline Contract
        """
        pass

    def test_apply_contract_edits_v1(self) -> None:
        """Test case for apply_contract_edits_v1

        Apply Contract Edits
        """
        pass

    def test_ask_moo_redline_v1(self) -> None:
        """Test case for ask_moo_redline_v1

        Ask Moo Redline
        """
        pass

    def test_editor_callback(self) -> None:
        """Test case for editor_callback

        Editor Callback
        """
        pass

    def test_fetch_document(self) -> None:
        """Test case for fetch_document

        Fetch Document
        """
        pass

    def test_get_document_html_v1(self) -> None:
        """Test case for get_document_html_v1

        Get Document Html
        """
        pass

    def test_get_editor_config(self) -> None:
        """Test case for get_editor_config

        Get Editor Config
        """
        pass

    def test_get_latest_redline_job_v1(self) -> None:
        """Test case for get_latest_redline_job_v1

        Get Latest Redline Job
        """
        pass

    def test_get_redline_edits(self) -> None:
        """Test case for get_redline_edits

        Get Redline Edits
        """
        pass

    def test_get_redline_job_v1(self) -> None:
        """Test case for get_redline_job_v1

        Get Redline Job
        """
        pass

    def test_save_redline_edit(self) -> None:
        """Test case for save_redline_edit

        Save Redline Edit
        """
        pass

    def test_upload_contract_for_editor(self) -> None:
        """Test case for upload_contract_for_editor

        Upload Contract For Editor
        """
        pass


if __name__ == '__main__':
    unittest.main()
