# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.feature_override_request import FeatureOverrideRequest

class TestFeatureOverrideRequest(unittest.TestCase):
    """FeatureOverrideRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FeatureOverrideRequest:
        """Test FeatureOverrideRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FeatureOverrideRequest`
        """
        model = FeatureOverrideRequest()
        if include_optional:
            return FeatureOverrideRequest(
                feature_key = '',
                currency = 'USD',
                override_price_micros = 56,
                override_discount_bps = 56
            )
        else:
            return FeatureOverrideRequest(
                feature_key = '',
        )
        """

    def testFeatureOverrideRequest(self):
        """Test FeatureOverrideRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
