# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.meter_validation_error import MeterValidationError

class TestMeterValidationError(unittest.TestCase):
    """MeterValidationError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MeterValidationError:
        """Test MeterValidationError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MeterValidationError`
        """
        model = MeterValidationError()
        if include_optional:
            return MeterValidationError(
                var_field = 'addons/pro/ratecards/token/featureKey',
                code = 'invalid_feature_key',
                message = 'not found feature by key',
                attributes = {externalId=019142cc-a016-796a-8113-1a942fecd26d}
            )
        else:
            return MeterValidationError(
                var_field = 'addons/pro/ratecards/token/featureKey',
                code = 'invalid_feature_key',
                message = 'not found feature by key',
        )
        """

    def testMeterValidationError(self):
        """Test MeterValidationError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
