# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moolabs.models.portal_token import PortalToken

class TestPortalToken(unittest.TestCase):
    """PortalToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PortalToken:
        """Test PortalToken
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PortalToken`
        """
        model = PortalToken()
        if include_optional:
            return PortalToken(
                id = '01G65Z755AFWAKHE12NY0CQ9FH',
                subject = 'customer-1',
                expires_at = '2023-01-01T01:01:01.001Z',
                expired = True,
                created_at = '2023-01-01T01:01:01.001Z',
                token = 'om_portal_IAnD3PpWW2A2Wr8m9jfzeHlGX8xmCXwG.y5q4S-AWqFu6qjfaFz0zQq4Ez28RsnyVwJffX5qxMvo',
                allowed_meter_slugs = [tokens_total]
            )
        else:
            return PortalToken(
                subject = 'customer-1',
        )
        """

    def testPortalToken(self):
        """Test PortalToken"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
