# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc10
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AutoTopupRuleResponse(BaseModel):
    """
    Response from creating an auto top-up rule.
    """ # noqa: E501
    id: StrictStr
    tenant_id: StrictStr
    pool_id: StrictStr
    wallet_id: StrictStr
    trigger_type: StrictStr
    trigger_value: StrictStr
    topup_amount_micros: StrictInt
    topup_cooldown_seconds: StrictInt
    max_topups_per_day: StrictInt
    payment_method_ref: StrictStr
    invoice_mode: StrictStr
    enabled: Optional[StrictBool] = True
    last_triggered_at: Optional[datetime] = None
    created_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "tenant_id", "pool_id", "wallet_id", "trigger_type", "trigger_value", "topup_amount_micros", "topup_cooldown_seconds", "max_topups_per_day", "payment_method_ref", "invoice_mode", "enabled", "last_triggered_at", "created_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AutoTopupRuleResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AutoTopupRuleResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "tenant_id": obj.get("tenant_id"),
            "pool_id": obj.get("pool_id"),
            "wallet_id": obj.get("wallet_id"),
            "trigger_type": obj.get("trigger_type"),
            "trigger_value": obj.get("trigger_value"),
            "topup_amount_micros": obj.get("topup_amount_micros"),
            "topup_cooldown_seconds": obj.get("topup_cooldown_seconds"),
            "max_topups_per_day": obj.get("max_topups_per_day"),
            "payment_method_ref": obj.get("payment_method_ref"),
            "invoice_mode": obj.get("invoice_mode"),
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else True,
            "last_triggered_at": obj.get("last_triggered_at"),
            "created_at": obj.get("created_at")
        })
        return _obj


