# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CaseInvoiceResponse(BaseModel):
    """
    Embedded invoice within a case response.
    """ # noqa: E501
    id: StrictStr
    case_id: StrictStr
    invoice_id: StrictStr
    invoice_number: Optional[StrictStr] = None
    amount_micros: StrictInt
    paid_micros: StrictInt
    disputed_micros: StrictInt
    credited_micros: StrictInt
    written_off_micros: StrictInt
    collectible_micros: Optional[StrictInt] = None
    currency_code: StrictStr
    base_currency_code: StrictStr
    fx_rate_snapshot: Optional[StrictStr] = None
    amount_base_micros: StrictInt
    paid_base_micros: StrictInt
    disputed_base_micros: StrictInt
    credited_base_micros: StrictInt
    written_off_base_micros: StrictInt
    collectible_base_micros: Optional[StrictInt] = None
    due_date: date
    issue_date: Optional[date] = None
    predicted_pay_date: Optional[date] = None
    invoice_status: Optional[StrictStr] = 'payment_pending'
    aging_bucket: StrictStr
    invoice_type: StrictStr
    voided_at: Optional[datetime] = None
    created_at: datetime
    updated_at: datetime
    __properties: ClassVar[List[str]] = ["id", "case_id", "invoice_id", "invoice_number", "amount_micros", "paid_micros", "disputed_micros", "credited_micros", "written_off_micros", "collectible_micros", "currency_code", "base_currency_code", "fx_rate_snapshot", "amount_base_micros", "paid_base_micros", "disputed_base_micros", "credited_base_micros", "written_off_base_micros", "collectible_base_micros", "due_date", "issue_date", "predicted_pay_date", "invoice_status", "aging_bucket", "invoice_type", "voided_at", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CaseInvoiceResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CaseInvoiceResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "case_id": obj.get("case_id"),
            "invoice_id": obj.get("invoice_id"),
            "invoice_number": obj.get("invoice_number"),
            "amount_micros": obj.get("amount_micros"),
            "paid_micros": obj.get("paid_micros"),
            "disputed_micros": obj.get("disputed_micros"),
            "credited_micros": obj.get("credited_micros"),
            "written_off_micros": obj.get("written_off_micros"),
            "collectible_micros": obj.get("collectible_micros"),
            "currency_code": obj.get("currency_code"),
            "base_currency_code": obj.get("base_currency_code"),
            "fx_rate_snapshot": obj.get("fx_rate_snapshot"),
            "amount_base_micros": obj.get("amount_base_micros"),
            "paid_base_micros": obj.get("paid_base_micros"),
            "disputed_base_micros": obj.get("disputed_base_micros"),
            "credited_base_micros": obj.get("credited_base_micros"),
            "written_off_base_micros": obj.get("written_off_base_micros"),
            "collectible_base_micros": obj.get("collectible_base_micros"),
            "due_date": obj.get("due_date"),
            "issue_date": obj.get("issue_date"),
            "predicted_pay_date": obj.get("predicted_pay_date"),
            "invoice_status": obj.get("invoice_status") if obj.get("invoice_status") is not None else 'payment_pending',
            "aging_bucket": obj.get("aging_bucket"),
            "invoice_type": obj.get("invoice_type"),
            "voided_at": obj.get("voided_at"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


