# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class ChannelPreferenceCreate(BaseModel):
    """
    Body for creating/updating a channel preference.
    """ # noqa: E501
    channel: StrictStr = Field(description="One of: email, sms, phone, portal")
    consent_status: Optional[StrictStr] = Field(default='unknown', description="One of: unknown, granted, denied, revoked")
    opt_out: Optional[StrictBool] = False
    suppressed_until: Optional[datetime] = None
    consent_source: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    consent_captured_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["channel", "consent_status", "opt_out", "suppressed_until", "consent_source", "consent_captured_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChannelPreferenceCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChannelPreferenceCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "channel": obj.get("channel"),
            "consent_status": obj.get("consent_status") if obj.get("consent_status") is not None else 'unknown',
            "opt_out": obj.get("opt_out") if obj.get("opt_out") is not None else False,
            "suppressed_until": obj.get("suppressed_until"),
            "consent_source": obj.get("consent_source"),
            "consent_captured_at": obj.get("consent_captured_at")
        })
        return _obj


