# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from moolabs.models.fx_rate_to_reporting import FxRateToReporting
from moolabs.models.line_item_create import LineItemCreate
from moolabs.models.observed_total_cost import ObservedTotalCost
from moolabs.models.reporting_total_cost import ReportingTotalCost
from typing import Optional, Set
from typing_extensions import Self

class CostEventIngest(BaseModel):
    """
    CostEventIngest
    """ # noqa: E501
    tenant_id: StrictStr
    idempotency_key: Annotated[str, Field(strict=True, max_length=256)]
    trace_id: Optional[Annotated[str, Field(strict=True, max_length=128)]] = None
    root_span_id: Optional[Annotated[str, Field(strict=True, max_length=128)]] = None
    span_id: Optional[Annotated[str, Field(strict=True, max_length=128)]] = None
    parent_span_id: Optional[Annotated[str, Field(strict=True, max_length=128)]] = None
    request_id: Optional[Annotated[str, Field(strict=True, max_length=256)]] = None
    customer_id: Optional[StrictStr] = None
    feature_id: Optional[StrictStr] = None
    plan_id: Optional[StrictStr] = None
    subscription_id: Optional[StrictStr] = None
    workflow_id: Optional[Annotated[str, Field(strict=True, max_length=256)]] = None
    workflow_version: Optional[Annotated[str, Field(strict=True, max_length=64)]] = None
    provider: Annotated[str, Field(strict=True, max_length=64)]
    model_requested: Optional[Annotated[str, Field(strict=True, max_length=128)]] = None
    model_responded: Optional[Annotated[str, Field(strict=True, max_length=128)]] = None
    operation_type: Optional[Annotated[str, Field(strict=True, max_length=64)]] = None
    component_type: Optional[Annotated[str, Field(strict=True, max_length=64)]] = None
    observed_total_cost: ObservedTotalCost
    currency: Annotated[str, Field(strict=True, max_length=3)]
    reporting_total_cost: ReportingTotalCost
    reporting_currency: Optional[Annotated[str, Field(strict=True, max_length=3)]] = 'USD'
    fx_rate_to_reporting: Optional[FxRateToReporting] = None
    latency_ms: Optional[StrictInt] = None
    cache_hit: Optional[StrictBool] = False
    environment: Optional[Annotated[str, Field(strict=True, max_length=32)]] = 'production'
    usage_event_id: Optional[StrictStr] = None
    ingestion_path: Optional[Annotated[str, Field(strict=True, max_length=16)]] = 'sdk'
    ingestion_source: Optional[Annotated[str, Field(strict=True, max_length=64)]] = None
    tags: Optional[Dict[str, Any]] = None
    provider_metadata: Optional[Dict[str, Any]] = None
    otel_attributes: Optional[Dict[str, Any]] = None
    event_timestamp: datetime
    line_items: Optional[List[LineItemCreate]] = None
    __properties: ClassVar[List[str]] = ["tenant_id", "idempotency_key", "trace_id", "root_span_id", "span_id", "parent_span_id", "request_id", "customer_id", "feature_id", "plan_id", "subscription_id", "workflow_id", "workflow_version", "provider", "model_requested", "model_responded", "operation_type", "component_type", "observed_total_cost", "currency", "reporting_total_cost", "reporting_currency", "fx_rate_to_reporting", "latency_ms", "cache_hit", "environment", "usage_event_id", "ingestion_path", "ingestion_source", "tags", "provider_metadata", "otel_attributes", "event_timestamp", "line_items"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CostEventIngest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of observed_total_cost
        if self.observed_total_cost:
            _dict['observed_total_cost'] = self.observed_total_cost.to_dict()
        # override the default output from pydantic by calling `to_dict()` of reporting_total_cost
        if self.reporting_total_cost:
            _dict['reporting_total_cost'] = self.reporting_total_cost.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fx_rate_to_reporting
        if self.fx_rate_to_reporting:
            _dict['fx_rate_to_reporting'] = self.fx_rate_to_reporting.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in line_items (list)
        _items = []
        if self.line_items:
            for _item_line_items in self.line_items:
                if _item_line_items:
                    _items.append(_item_line_items.to_dict())
            _dict['line_items'] = _items
        # set to None if fx_rate_to_reporting (nullable) is None
        # and model_fields_set contains the field
        if self.fx_rate_to_reporting is None and "fx_rate_to_reporting" in self.model_fields_set:
            _dict['fx_rate_to_reporting'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CostEventIngest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tenant_id": obj.get("tenant_id"),
            "idempotency_key": obj.get("idempotency_key"),
            "trace_id": obj.get("trace_id"),
            "root_span_id": obj.get("root_span_id"),
            "span_id": obj.get("span_id"),
            "parent_span_id": obj.get("parent_span_id"),
            "request_id": obj.get("request_id"),
            "customer_id": obj.get("customer_id"),
            "feature_id": obj.get("feature_id"),
            "plan_id": obj.get("plan_id"),
            "subscription_id": obj.get("subscription_id"),
            "workflow_id": obj.get("workflow_id"),
            "workflow_version": obj.get("workflow_version"),
            "provider": obj.get("provider"),
            "model_requested": obj.get("model_requested"),
            "model_responded": obj.get("model_responded"),
            "operation_type": obj.get("operation_type"),
            "component_type": obj.get("component_type"),
            "observed_total_cost": ObservedTotalCost.from_dict(obj["observed_total_cost"]) if obj.get("observed_total_cost") is not None else None,
            "currency": obj.get("currency"),
            "reporting_total_cost": ReportingTotalCost.from_dict(obj["reporting_total_cost"]) if obj.get("reporting_total_cost") is not None else None,
            "reporting_currency": obj.get("reporting_currency") if obj.get("reporting_currency") is not None else 'USD',
            "fx_rate_to_reporting": FxRateToReporting.from_dict(obj["fx_rate_to_reporting"]) if obj.get("fx_rate_to_reporting") is not None else None,
            "latency_ms": obj.get("latency_ms"),
            "cache_hit": obj.get("cache_hit") if obj.get("cache_hit") is not None else False,
            "environment": obj.get("environment") if obj.get("environment") is not None else 'production',
            "usage_event_id": obj.get("usage_event_id"),
            "ingestion_path": obj.get("ingestion_path") if obj.get("ingestion_path") is not None else 'sdk',
            "ingestion_source": obj.get("ingestion_source"),
            "tags": obj.get("tags"),
            "provider_metadata": obj.get("provider_metadata"),
            "otel_attributes": obj.get("otel_attributes"),
            "event_timestamp": obj.get("event_timestamp"),
            "line_items": [LineItemCreate.from_dict(_item) for _item in obj["line_items"]] if obj.get("line_items") is not None else None
        })
        return _obj


