# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class CreateRateCardRequest(BaseModel):
    """
    Request to create a rate card.
    """ # noqa: E501
    tenant_id: StrictStr = Field(description="Tenant identifier")
    plan_id: Optional[StrictStr] = Field(default=None, description="Plan ID for plan-scoped rate cards (optional)")
    feature_key: Annotated[str, Field(min_length=1, strict=True, max_length=255)] = Field(description="Feature key")
    currency: Optional[Annotated[str, Field(strict=True, max_length=3)]] = Field(default='USD', description="Currency code (ISO 4217)")
    version: Annotated[str, Field(min_length=1, strict=True, max_length=64)] = Field(description="Rate card version")
    effective_from: datetime = Field(description="Effective from timestamp")
    effective_to: Optional[datetime] = Field(default=None, description="Effective to timestamp (None = indefinite)")
    pricing_model: Dict[str, Any] = Field(description="Pricing model (JSON object)")
    __properties: ClassVar[List[str]] = ["tenant_id", "plan_id", "feature_key", "currency", "version", "effective_from", "effective_to", "pricing_model"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateRateCardRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateRateCardRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tenant_id": obj.get("tenant_id"),
            "plan_id": obj.get("plan_id"),
            "feature_key": obj.get("feature_key"),
            "currency": obj.get("currency") if obj.get("currency") is not None else 'USD',
            "version": obj.get("version"),
            "effective_from": obj.get("effective_from"),
            "effective_to": obj.get("effective_to"),
            "pricing_model": obj.get("pricing_model")
        })
        return _obj


