# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from moolabs.models.customer_create import CustomerCreate
from moolabs.models.customer_id import CustomerId
from moolabs.models.customer_key import CustomerKey
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

CREATESTRIPECHECKOUTSESSIONREQUESTCUSTOMER_ANY_OF_SCHEMAS = ["CustomerCreate", "CustomerId", "CustomerKey"]

class CreateStripeCheckoutSessionRequestCustomer(BaseModel):
    """
    Provide a customer ID or key to use an existing OpenMeter customer. or provide a customer object to create a new customer.
    """

    # data type: CustomerId
    anyof_schema_1_validator: Optional[CustomerId] = None
    # data type: CustomerKey
    anyof_schema_2_validator: Optional[CustomerKey] = None
    # data type: CustomerCreate
    anyof_schema_3_validator: Optional[CustomerCreate] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[CustomerCreate, CustomerId, CustomerKey]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "CustomerCreate", "CustomerId", "CustomerKey" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = CreateStripeCheckoutSessionRequestCustomer.model_construct()
        error_messages = []
        # validate data type: CustomerId
        if not isinstance(v, CustomerId):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CustomerId`")
        else:
            return v

        # validate data type: CustomerKey
        if not isinstance(v, CustomerKey):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CustomerKey`")
        else:
            return v

        # validate data type: CustomerCreate
        if not isinstance(v, CustomerCreate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CustomerCreate`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in CreateStripeCheckoutSessionRequestCustomer with anyOf schemas: CustomerCreate, CustomerId, CustomerKey. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[CustomerId] = None
        try:
            instance.actual_instance = CustomerId.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[CustomerKey] = None
        try:
            instance.actual_instance = CustomerKey.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[CustomerCreate] = None
        try:
            instance.actual_instance = CustomerCreate.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into CreateStripeCheckoutSessionRequestCustomer with anyOf schemas: CustomerCreate, CustomerId, CustomerKey. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], CustomerCreate, CustomerId, CustomerKey]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


