# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from moolabs.models.app_status import AppStatus
from moolabs.models.marketplace_listing import MarketplaceListing
from typing import Optional, Set
from typing_extensions import Self

class CustomInvoicingApp(BaseModel):
    """
    Custom Invoicing app can be used for interface with any invoicing or payment system.  This app provides ways to manipulate invoices and payments, however the integration must rely on Notifications API to get notified about invoice changes.
    """ # noqa: E501
    id: Annotated[str, Field(strict=True)] = Field(description="A unique identifier for the resource.")
    name: Annotated[str, Field(min_length=1, strict=True, max_length=256)] = Field(description="Human-readable name for the resource. Between 1 and 256 characters.")
    description: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = Field(default=None, description="Optional description of the resource. Maximum 1024 characters.")
    metadata: Optional[Dict[str, StrictStr]] = Field(default=None, description="Additional metadata for the resource.")
    created_at: datetime = Field(description="Timestamp of when the resource was created.", alias="createdAt")
    updated_at: datetime = Field(description="Timestamp of when the resource was last updated.", alias="updatedAt")
    deleted_at: Optional[datetime] = Field(default=None, description="Timestamp of when the resource was permanently deleted.", alias="deletedAt")
    listing: MarketplaceListing = Field(description="The marketplace listing that this installed app is based on.")
    status: AppStatus = Field(description="Status of the app connection.")
    type: StrictStr = Field(description="The app's type is CustomInvoicing.")
    enable_draft_sync_hook: StrictBool = Field(description="Enable draft.sync hook.  If the hook is not enabled, the invoice will be progressed to the next state automatically.", alias="enableDraftSyncHook")
    enable_issuing_sync_hook: StrictBool = Field(description="Enable issuing.sync hook.  If the hook is not enabled, the invoice will be progressed to the next state automatically.", alias="enableIssuingSyncHook")
    __properties: ClassVar[List[str]] = ["id", "name", "description", "metadata", "createdAt", "updatedAt", "deletedAt", "listing", "status", "type", "enableDraftSyncHook", "enableIssuingSyncHook"]

    @field_validator('id')
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[0-7][0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{25}$", value):
            raise ValueError(r"must validate the regular expression /^[0-7][0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{25}$/")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['custom_invoicing']):
            raise ValueError("must be one of enum values ('custom_invoicing')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomInvoicingApp from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "created_at",
            "updated_at",
            "deleted_at",
            "listing",
            "status",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of listing
        if self.listing:
            _dict['listing'] = self.listing.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomInvoicingApp from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "metadata": obj.get("metadata"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "deletedAt": obj.get("deletedAt"),
            "listing": MarketplaceListing.from_dict(obj["listing"]) if obj.get("listing") is not None else None,
            "status": obj.get("status"),
            "type": obj.get("type"),
            "enableDraftSyncHook": obj.get("enableDraftSyncHook"),
            "enableIssuingSyncHook": obj.get("enableIssuingSyncHook")
        })
        return _obj


