# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from moolabs.models.aging_report_response import AgingReportResponse
from moolabs.models.cei_response import CEIResponse
from moolabs.models.dispute_summary_response import DisputeSummaryResponse
from moolabs.models.dso_response import DSOResponse
from moolabs.models.ptp_summary_response import PTPSummaryResponse
from typing import Optional, Set
from typing_extensions import Self

class DashboardOverviewResponse(BaseModel):
    """
    DashboardOverviewResponse
    """ # noqa: E501
    aging: AgingReportResponse
    dso: DSOResponse
    cei: CEIResponse
    dispute_summary: DisputeSummaryResponse
    ptp_summary: PTPSummaryResponse
    __properties: ClassVar[List[str]] = ["aging", "dso", "cei", "dispute_summary", "ptp_summary"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DashboardOverviewResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of aging
        if self.aging:
            _dict['aging'] = self.aging.to_dict()
        # override the default output from pydantic by calling `to_dict()` of dso
        if self.dso:
            _dict['dso'] = self.dso.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cei
        if self.cei:
            _dict['cei'] = self.cei.to_dict()
        # override the default output from pydantic by calling `to_dict()` of dispute_summary
        if self.dispute_summary:
            _dict['dispute_summary'] = self.dispute_summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ptp_summary
        if self.ptp_summary:
            _dict['ptp_summary'] = self.ptp_summary.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DashboardOverviewResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "aging": AgingReportResponse.from_dict(obj["aging"]) if obj.get("aging") is not None else None,
            "dso": DSOResponse.from_dict(obj["dso"]) if obj.get("dso") is not None else None,
            "cei": CEIResponse.from_dict(obj["cei"]) if obj.get("cei") is not None else None,
            "dispute_summary": DisputeSummaryResponse.from_dict(obj["dispute_summary"]) if obj.get("dispute_summary") is not None else None,
            "ptp_summary": PTPSummaryResponse.from_dict(obj["ptp_summary"]) if obj.get("ptp_summary") is not None else None
        })
        return _obj


