# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from moolabs.models.amount1 import Amount1
from moolabs.models.rate_card_payload import RateCardPayload
from typing import Optional, Set
from typing_extensions import Self

class EntitlementPayload(BaseModel):
    """
    EntitlementPayload
    """ # noqa: E501
    entitlement_id: StrictStr = Field(alias="entitlementId")
    feature_key: StrictStr = Field(alias="featureKey")
    entitlement_type: StrictStr = Field(alias="entitlementType")
    amount: Optional[Amount1] = None
    rate_card: Optional[RateCardPayload] = Field(default=None, alias="rateCard")
    __properties: ClassVar[List[str]] = ["entitlementId", "featureKey", "entitlementType", "amount", "rateCard"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntitlementPayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount
        if self.amount:
            _dict['amount'] = self.amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rate_card
        if self.rate_card:
            _dict['rateCard'] = self.rate_card.to_dict()
        # set to None if amount (nullable) is None
        # and model_fields_set contains the field
        if self.amount is None and "amount" in self.model_fields_set:
            _dict['amount'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntitlementPayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "entitlementId": obj.get("entitlementId"),
            "featureKey": obj.get("featureKey"),
            "entitlementType": obj.get("entitlementType"),
            "amount": Amount1.from_dict(obj["amount"]) if obj.get("amount") is not None else None,
            "rateCard": RateCardPayload.from_dict(obj["rateCard"]) if obj.get("rateCard") is not None else None
        })
        return _obj


