# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0-rc4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from moolabs.models.period import Period
from moolabs.models.recurring_period import RecurringPeriod
from typing import Optional, Set
from typing_extensions import Self

class EntitlementMeteredCalculatedFields(BaseModel):
    """
    Calculated fields for metered entitlements.
    """ # noqa: E501
    last_reset: datetime = Field(description="The time the last reset happened.", alias="lastReset")
    current_usage_period: Period = Field(description="The current usage period.", alias="currentUsagePeriod")
    measure_usage_from: datetime = Field(description="The time from which usage is measured. If not specified on creation, defaults to entitlement creation time.", alias="measureUsageFrom")
    usage_period: RecurringPeriod = Field(description="THe usage period of the entitlement.", alias="usagePeriod")
    __properties: ClassVar[List[str]] = ["lastReset", "currentUsagePeriod", "measureUsageFrom", "usagePeriod"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntitlementMeteredCalculatedFields from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "last_reset",
            "current_usage_period",
            "measure_usage_from",
            "usage_period",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of current_usage_period
        if self.current_usage_period:
            _dict['currentUsagePeriod'] = self.current_usage_period.to_dict()
        # override the default output from pydantic by calling `to_dict()` of usage_period
        if self.usage_period:
            _dict['usagePeriod'] = self.usage_period.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntitlementMeteredCalculatedFields from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "lastReset": obj.get("lastReset"),
            "currentUsagePeriod": Period.from_dict(obj["currentUsagePeriod"]) if obj.get("currentUsagePeriod") is not None else None,
            "measureUsageFrom": obj.get("measureUsageFrom"),
            "usagePeriod": RecurringPeriod.from_dict(obj["usagePeriod"]) if obj.get("usagePeriod") is not None else None
        })
        return _obj


