# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0-rc5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from moolabs.models.invoice_line_app_external_ids import InvoiceLineAppExternalIds
from moolabs.models.invoice_line_discounts import InvoiceLineDiscounts
from moolabs.models.invoice_line_managed_by import InvoiceLineManagedBy
from moolabs.models.invoice_line_status import InvoiceLineStatus
from moolabs.models.invoice_line_subscription_reference import InvoiceLineSubscriptionReference
from moolabs.models.invoice_line_tax_item import InvoiceLineTaxItem
from moolabs.models.invoice_line_types import InvoiceLineTypes
from moolabs.models.invoice_reference import InvoiceReference
from moolabs.models.invoice_totals import InvoiceTotals
from moolabs.models.period import Period
from moolabs.models.tax_config import TaxConfig
from typing import Optional, Set
from typing_extensions import Self

class InvoiceLineBase(BaseModel):
    """
    InvoiceLine represents a single item or service sold to the customer.  This is a base class for all line types, and should not be used directly.
    """ # noqa: E501
    name: Annotated[str, Field(min_length=1, strict=True, max_length=256)] = Field(description="Human-readable name for the resource. Between 1 and 256 characters.")
    description: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = Field(default=None, description="Optional description of the resource. Maximum 1024 characters.")
    metadata: Optional[Dict[str, StrictStr]] = Field(default=None, description="Additional metadata for the resource.")
    created_at: datetime = Field(description="Timestamp of when the resource was created.", alias="createdAt")
    updated_at: datetime = Field(description="Timestamp of when the resource was last updated.", alias="updatedAt")
    deleted_at: Optional[datetime] = Field(default=None, description="Timestamp of when the resource was permanently deleted.", alias="deletedAt")
    id: Annotated[str, Field(strict=True)] = Field(description="ID of the line.")
    type: InvoiceLineTypes = Field(description="Type of the line.  A line's type cannot be changed after creation.")
    managed_by: InvoiceLineManagedBy = Field(description="managedBy specifies if the line is manually added via the api or managed by OpenMeter.", alias="managedBy")
    status: InvoiceLineStatus = Field(description="Status of the line.  External calls always create valid lines, other line types are managed by the billing engine of OpenMeter.")
    discounts: Optional[InvoiceLineDiscounts] = Field(default=None, description="Discounts detailes applied to this line.  New discounts can be added via the invoice's discounts API, to facilitate discounts that are affecting multiple lines.")
    invoice: Optional[InvoiceReference] = Field(default=None, description="The invoice this item belongs to.")
    currency: Annotated[str, Field(min_length=3, strict=True, max_length=3)] = Field(description="The currency of this line.")
    taxes: Optional[List[InvoiceLineTaxItem]] = Field(default=None, description="Taxes applied to the invoice totals.")
    tax_config: Optional[TaxConfig] = Field(default=None, description="Tax config specify the tax configuration for this line.", alias="taxConfig")
    totals: InvoiceTotals = Field(description="Totals for this line.")
    period: Period = Field(description="Period of the line item applies to for revenue recognition pruposes.  Billing always treats periods as start being inclusive and end being exclusive.")
    invoice_at: datetime = Field(description="The time this line item should be invoiced.", alias="invoiceAt")
    external_ids: Optional[InvoiceLineAppExternalIds] = Field(default=None, description="External IDs of the invoice in other apps such as Stripe.", alias="externalIds")
    subscription: Optional[InvoiceLineSubscriptionReference] = Field(default=None, description="Subscription are the references to the subscritpions that this line is related to.")
    __properties: ClassVar[List[str]] = ["name", "description", "metadata", "createdAt", "updatedAt", "deletedAt", "id", "type", "managedBy", "status", "discounts", "invoice", "currency", "taxes", "taxConfig", "totals", "period", "invoiceAt", "externalIds", "subscription"]

    @field_validator('id')
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[0-7][0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{25}$", value):
            raise ValueError(r"must validate the regular expression /^[0-7][0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{25}$/")
        return value

    @field_validator('currency')
    def currency_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[A-Z]{3}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z]{3}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InvoiceLineBase from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "created_at",
            "updated_at",
            "deleted_at",
            "type",
            "managed_by",
            "status",
            "discounts",
            "totals",
            "external_ids",
            "subscription",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of discounts
        if self.discounts:
            _dict['discounts'] = self.discounts.to_dict()
        # override the default output from pydantic by calling `to_dict()` of invoice
        if self.invoice:
            _dict['invoice'] = self.invoice.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in taxes (list)
        _items = []
        if self.taxes:
            for _item_taxes in self.taxes:
                if _item_taxes:
                    _items.append(_item_taxes.to_dict())
            _dict['taxes'] = _items
        # override the default output from pydantic by calling `to_dict()` of tax_config
        if self.tax_config:
            _dict['taxConfig'] = self.tax_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of totals
        if self.totals:
            _dict['totals'] = self.totals.to_dict()
        # override the default output from pydantic by calling `to_dict()` of period
        if self.period:
            _dict['period'] = self.period.to_dict()
        # override the default output from pydantic by calling `to_dict()` of external_ids
        if self.external_ids:
            _dict['externalIds'] = self.external_ids.to_dict()
        # override the default output from pydantic by calling `to_dict()` of subscription
        if self.subscription:
            _dict['subscription'] = self.subscription.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InvoiceLineBase from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "metadata": obj.get("metadata"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "deletedAt": obj.get("deletedAt"),
            "id": obj.get("id"),
            "type": obj.get("type"),
            "managedBy": obj.get("managedBy"),
            "status": obj.get("status"),
            "discounts": InvoiceLineDiscounts.from_dict(obj["discounts"]) if obj.get("discounts") is not None else None,
            "invoice": InvoiceReference.from_dict(obj["invoice"]) if obj.get("invoice") is not None else None,
            "currency": obj.get("currency"),
            "taxes": [InvoiceLineTaxItem.from_dict(_item) for _item in obj["taxes"]] if obj.get("taxes") is not None else None,
            "taxConfig": TaxConfig.from_dict(obj["taxConfig"]) if obj.get("taxConfig") is not None else None,
            "totals": InvoiceTotals.from_dict(obj["totals"]) if obj.get("totals") is not None else None,
            "period": Period.from_dict(obj["period"]) if obj.get("period") is not None else None,
            "invoiceAt": obj.get("invoiceAt"),
            "externalIds": InvoiceLineAppExternalIds.from_dict(obj["externalIds"]) if obj.get("externalIds") is not None else None,
            "subscription": InvoiceLineSubscriptionReference.from_dict(obj["subscription"]) if obj.get("subscription") is not None else None
        })
        return _obj


