# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from moolabs.models.invoice_usage_based_rate_card import InvoiceUsageBasedRateCard
from moolabs.models.period import Period
from moolabs.models.rate_card_usage_based_price import RateCardUsageBasedPrice
from moolabs.models.tax_config import TaxConfig
from typing import Optional, Set
from typing_extensions import Self

class InvoiceSimulationLine(BaseModel):
    """
    InvoiceSimulationLine represents a usage-based line item that can be input to the simulation endpoint.
    """ # noqa: E501
    name: Annotated[str, Field(min_length=1, strict=True, max_length=256)] = Field(description="Human-readable name for the resource. Between 1 and 256 characters.")
    description: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = Field(default=None, description="Optional description of the resource. Maximum 1024 characters.")
    metadata: Optional[Dict[str, StrictStr]] = Field(default=None, description="Additional metadata for the resource.")
    tax_config: Optional[TaxConfig] = Field(default=None, description="Tax config specify the tax configuration for this line.", alias="taxConfig")
    period: Period = Field(description="Period of the line item applies to for revenue recognition pruposes.  Billing always treats periods as start being inclusive and end being exclusive.")
    invoice_at: datetime = Field(description="The time this line item should be invoiced.", alias="invoiceAt")
    price: Optional[RateCardUsageBasedPrice] = Field(default=None, description="Price of the usage-based item being sold.")
    feature_key: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = Field(default=None, description="The feature that the usage is based on.", alias="featureKey")
    rate_card: Optional[InvoiceUsageBasedRateCard] = Field(default=None, description="The rate card that is used for this line.  The rate card captures the intent of the price and discounts for the usage-based item.", alias="rateCard")
    quantity: Annotated[str, Field(strict=True)] = Field(description="The quantity of the item being sold.")
    pre_line_period_quantity: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="The quantity of the item used before this line's period, if the line is billed progressively.", alias="preLinePeriodQuantity")
    id: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="ID of the line. If not specified it will be auto-generated.  When discounts are specified, this must be provided, so that the discount can reference it.")
    __properties: ClassVar[List[str]] = ["name", "description", "metadata", "taxConfig", "period", "invoiceAt", "price", "featureKey", "rateCard", "quantity", "preLinePeriodQuantity", "id"]

    @field_validator('feature_key')
    def feature_key_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-z0-9]+(?:_[a-z0-9]+)*$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9]+(?:_[a-z0-9]+)*$/")
        return value

    @field_validator('quantity')
    def quantity_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^\-?[0-9]+(\.[0-9]+)?$", value):
            raise ValueError(r"must validate the regular expression /^\-?[0-9]+(\.[0-9]+)?$/")
        return value

    @field_validator('pre_line_period_quantity')
    def pre_line_period_quantity_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\-?[0-9]+(\.[0-9]+)?$", value):
            raise ValueError(r"must validate the regular expression /^\-?[0-9]+(\.[0-9]+)?$/")
        return value

    @field_validator('id')
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[0-7][0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{25}$", value):
            raise ValueError(r"must validate the regular expression /^[0-7][0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{25}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InvoiceSimulationLine from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of tax_config
        if self.tax_config:
            _dict['taxConfig'] = self.tax_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of period
        if self.period:
            _dict['period'] = self.period.to_dict()
        # override the default output from pydantic by calling `to_dict()` of price
        if self.price:
            _dict['price'] = self.price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rate_card
        if self.rate_card:
            _dict['rateCard'] = self.rate_card.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InvoiceSimulationLine from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "metadata": obj.get("metadata"),
            "taxConfig": TaxConfig.from_dict(obj["taxConfig"]) if obj.get("taxConfig") is not None else None,
            "period": Period.from_dict(obj["period"]) if obj.get("period") is not None else None,
            "invoiceAt": obj.get("invoiceAt"),
            "price": RateCardUsageBasedPrice.from_dict(obj["price"]) if obj.get("price") is not None else None,
            "featureKey": obj.get("featureKey"),
            "rateCard": InvoiceUsageBasedRateCard.from_dict(obj["rateCard"]) if obj.get("rateCard") is not None else None,
            "quantity": obj.get("quantity"),
            "preLinePeriodQuantity": obj.get("preLinePeriodQuantity"),
            "id": obj.get("id")
        })
        return _obj


