# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0-rc2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from moolabs.models.billing_party_replace_update import BillingPartyReplaceUpdate
from moolabs.models.invoice_line_replace_update import InvoiceLineReplaceUpdate
from moolabs.models.invoice_workflow_replace_update import InvoiceWorkflowReplaceUpdate
from typing import Optional, Set
from typing_extensions import Self

class InvoiceReplaceUpdate(BaseModel):
    """
    InvoiceReplaceUpdate represents the update model for an invoice.
    """ # noqa: E501
    description: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = Field(default=None, description="Optional description of the resource. Maximum 1024 characters.")
    metadata: Optional[Dict[str, StrictStr]] = Field(default=None, description="Additional metadata for the resource.")
    supplier: BillingPartyReplaceUpdate = Field(description="The supplier of the lines included in the invoice.")
    customer: BillingPartyReplaceUpdate = Field(description="The customer the invoice is sent to.")
    lines: List[InvoiceLineReplaceUpdate] = Field(description="The lines included in the invoice.")
    workflow: InvoiceWorkflowReplaceUpdate = Field(description="The workflow settings for the invoice.")
    __properties: ClassVar[List[str]] = ["description", "metadata", "supplier", "customer", "lines", "workflow"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InvoiceReplaceUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of supplier
        if self.supplier:
            _dict['supplier'] = self.supplier.to_dict()
        # override the default output from pydantic by calling `to_dict()` of customer
        if self.customer:
            _dict['customer'] = self.customer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in lines (list)
        _items = []
        if self.lines:
            for _item_lines in self.lines:
                if _item_lines:
                    _items.append(_item_lines.to_dict())
            _dict['lines'] = _items
        # override the default output from pydantic by calling `to_dict()` of workflow
        if self.workflow:
            _dict['workflow'] = self.workflow.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InvoiceReplaceUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "description": obj.get("description"),
            "metadata": obj.get("metadata"),
            "supplier": BillingPartyReplaceUpdate.from_dict(obj["supplier"]) if obj.get("supplier") is not None else None,
            "customer": BillingPartyReplaceUpdate.from_dict(obj["customer"]) if obj.get("customer") is not None else None,
            "lines": [InvoiceLineReplaceUpdate.from_dict(_item) for _item in obj["lines"]] if obj.get("lines") is not None else None,
            "workflow": InvoiceWorkflowReplaceUpdate.from_dict(obj["workflow"]) if obj.get("workflow") is not None else None
        })
        return _obj


