# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc8
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from moolabs.models.notification_rule_balance_threshold_create_request import NotificationRuleBalanceThresholdCreateRequest
from moolabs.models.notification_rule_entitlement_reset_create_request import NotificationRuleEntitlementResetCreateRequest
from moolabs.models.notification_rule_invoice_created_create_request import NotificationRuleInvoiceCreatedCreateRequest
from moolabs.models.notification_rule_invoice_updated_create_request import NotificationRuleInvoiceUpdatedCreateRequest
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

NOTIFICATIONRULECREATEREQUEST_ONE_OF_SCHEMAS = ["NotificationRuleBalanceThresholdCreateRequest", "NotificationRuleEntitlementResetCreateRequest", "NotificationRuleInvoiceCreatedCreateRequest", "NotificationRuleInvoiceUpdatedCreateRequest"]

class NotificationRuleCreateRequest(BaseModel):
    """
    Union type for requests creating new notification rule with certain type.
    """
    # data type: NotificationRuleBalanceThresholdCreateRequest
    oneof_schema_1_validator: Optional[NotificationRuleBalanceThresholdCreateRequest] = None
    # data type: NotificationRuleEntitlementResetCreateRequest
    oneof_schema_2_validator: Optional[NotificationRuleEntitlementResetCreateRequest] = None
    # data type: NotificationRuleInvoiceCreatedCreateRequest
    oneof_schema_3_validator: Optional[NotificationRuleInvoiceCreatedCreateRequest] = None
    # data type: NotificationRuleInvoiceUpdatedCreateRequest
    oneof_schema_4_validator: Optional[NotificationRuleInvoiceUpdatedCreateRequest] = None
    actual_instance: Optional[Union[NotificationRuleBalanceThresholdCreateRequest, NotificationRuleEntitlementResetCreateRequest, NotificationRuleInvoiceCreatedCreateRequest, NotificationRuleInvoiceUpdatedCreateRequest]] = None
    one_of_schemas: Set[str] = { "NotificationRuleBalanceThresholdCreateRequest", "NotificationRuleEntitlementResetCreateRequest", "NotificationRuleInvoiceCreatedCreateRequest", "NotificationRuleInvoiceUpdatedCreateRequest" }

    # CUSTOMIZED (moolabs override): `extra="forbid"` added so a caller
    # passing unknown kwargs to a oneOf wrapper class gets a
    # ValidationError instead of a silently-empty model whose
    # `actual_instance` stays None. Mirrors the same fix applied to
    # model_anyof.mustache — see comments there and the postmortem at
    # docs/superpowers/reviews/2026-05-18-sdk-bugs-missed-detection-postmortem.md.
    #
    # Safe for the deserialization path: `from_json` / `from_dict` below
    # uses `cls.model_construct()` which bypasses validation entirely.
    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
        extra="forbid",
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = NotificationRuleCreateRequest.model_construct()
        error_messages = []
        match = 0
        # validate data type: NotificationRuleBalanceThresholdCreateRequest
        if not isinstance(v, NotificationRuleBalanceThresholdCreateRequest):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NotificationRuleBalanceThresholdCreateRequest`")
        else:
            match += 1
        # validate data type: NotificationRuleEntitlementResetCreateRequest
        if not isinstance(v, NotificationRuleEntitlementResetCreateRequest):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NotificationRuleEntitlementResetCreateRequest`")
        else:
            match += 1
        # validate data type: NotificationRuleInvoiceCreatedCreateRequest
        if not isinstance(v, NotificationRuleInvoiceCreatedCreateRequest):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NotificationRuleInvoiceCreatedCreateRequest`")
        else:
            match += 1
        # validate data type: NotificationRuleInvoiceUpdatedCreateRequest
        if not isinstance(v, NotificationRuleInvoiceUpdatedCreateRequest):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NotificationRuleInvoiceUpdatedCreateRequest`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in NotificationRuleCreateRequest with oneOf schemas: NotificationRuleBalanceThresholdCreateRequest, NotificationRuleEntitlementResetCreateRequest, NotificationRuleInvoiceCreatedCreateRequest, NotificationRuleInvoiceUpdatedCreateRequest. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in NotificationRuleCreateRequest with oneOf schemas: NotificationRuleBalanceThresholdCreateRequest, NotificationRuleEntitlementResetCreateRequest, NotificationRuleInvoiceCreatedCreateRequest, NotificationRuleInvoiceUpdatedCreateRequest. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into NotificationRuleBalanceThresholdCreateRequest
        try:
            instance.actual_instance = NotificationRuleBalanceThresholdCreateRequest.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NotificationRuleEntitlementResetCreateRequest
        try:
            instance.actual_instance = NotificationRuleEntitlementResetCreateRequest.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NotificationRuleInvoiceCreatedCreateRequest
        try:
            instance.actual_instance = NotificationRuleInvoiceCreatedCreateRequest.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NotificationRuleInvoiceUpdatedCreateRequest
        try:
            instance.actual_instance = NotificationRuleInvoiceUpdatedCreateRequest.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into NotificationRuleCreateRequest with oneOf schemas: NotificationRuleBalanceThresholdCreateRequest, NotificationRuleEntitlementResetCreateRequest, NotificationRuleInvoiceCreatedCreateRequest, NotificationRuleInvoiceUpdatedCreateRequest. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into NotificationRuleCreateRequest with oneOf schemas: NotificationRuleBalanceThresholdCreateRequest, NotificationRuleEntitlementResetCreateRequest, NotificationRuleInvoiceCreatedCreateRequest, NotificationRuleInvoiceUpdatedCreateRequest. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], NotificationRuleBalanceThresholdCreateRequest, NotificationRuleEntitlementResetCreateRequest, NotificationRuleInvoiceCreatedCreateRequest, NotificationRuleInvoiceUpdatedCreateRequest]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


