# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0-rc6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class NotificationChannelWebhook(BaseModel):
    """
    Notification channel with webhook type.
    """ # noqa: E501
    created_at: datetime = Field(description="Timestamp of when the resource was created.", alias="createdAt")
    updated_at: datetime = Field(description="Timestamp of when the resource was last updated.", alias="updatedAt")
    deleted_at: Optional[datetime] = Field(default=None, description="Timestamp of when the resource was permanently deleted.", alias="deletedAt")
    id: Annotated[str, Field(strict=True)] = Field(description="Identifies the notification channel.")
    type: StrictStr = Field(description="Notification channel type.")
    name: Annotated[str, Field(min_length=1, strict=True, max_length=256)] = Field(description="User friendly name of the channel.")
    disabled: Optional[StrictBool] = Field(default=False, description="Whether the channel is disabled or not.")
    annotations: Optional[Dict[str, Any]] = Field(default=None, description="Set of key-value pairs managed by the system. Cannot be modified by user.")
    metadata: Optional[Dict[str, StrictStr]] = Field(default=None, description="Additional metadata for the resource.")
    url: StrictStr = Field(description="Webhook URL where the notification is sent.")
    custom_headers: Optional[Dict[str, StrictStr]] = Field(default=None, description="Custom HTTP headers sent as part of the webhook request.", alias="customHeaders")
    signing_secret: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Signing secret used for webhook request validation on the receiving end.  Format: `base64` encoded random bytes optionally prefixed with `whsec_`. Recommended size: 24", alias="signingSecret")
    __properties: ClassVar[List[str]] = ["createdAt", "updatedAt", "deletedAt", "id", "type", "name", "disabled", "annotations", "metadata", "url", "customHeaders", "signingSecret"]

    @field_validator('id')
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[0-7][0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{25}$", value):
            raise ValueError(r"must validate the regular expression /^[0-7][0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{25}$/")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['WEBHOOK']):
            raise ValueError("must be one of enum values ('WEBHOOK')")
        return value

    @field_validator('signing_secret')
    def signing_secret_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(whsec_)?[a-zA-Z0-9+\/=]{32,100}$", value):
            raise ValueError(r"must validate the regular expression /^(whsec_)?[a-zA-Z0-9+\/=]{32,100}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NotificationChannelWebhook from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "created_at",
            "updated_at",
            "deleted_at",
            "id",
            "annotations",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NotificationChannelWebhook from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "deletedAt": obj.get("deletedAt"),
            "id": obj.get("id"),
            "type": obj.get("type"),
            "name": obj.get("name"),
            "disabled": obj.get("disabled") if obj.get("disabled") is not None else False,
            "annotations": obj.get("annotations"),
            "metadata": obj.get("metadata"),
            "url": obj.get("url"),
            "customHeaders": obj.get("customHeaders"),
            "signingSecret": obj.get("signingSecret")
        })
        return _obj


