# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ProRatingMode(str, Enum):
    """
    Pro-rating mode options for handling billing period changes.
    """

    """
    allowed enum values
    """
    PRORATE_PRICES = 'prorate_prices'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProRatingMode from a JSON string"""
        return cls(json.loads(json_str))


