# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class QuoteLineItemInput(BaseModel):
    """
    QuoteLineItemInput
    """ # noqa: E501
    line_no: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    sku_ref: Annotated[str, Field(min_length=1, strict=True)]
    feature_key: Optional[StrictStr] = None
    sku_version: Optional[StrictStr] = None
    rate_card_ref: Optional[StrictStr] = None
    plan_id: Optional[StrictStr] = None
    subscription_id: Optional[StrictStr] = None
    plan_version: Optional[StrictStr] = None
    quantity: Optional[StrictStr] = '1'
    quantity_unit: Optional[StrictStr] = 'unit'
    pricing_basis: Optional[StrictStr] = 'recurring'
    requested_discount: Optional[Dict[str, Any]] = None
    feature_overrides: Optional[Annotated[List[Dict[str, Any]], Field(max_length=20)]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["line_no", "sku_ref", "feature_key", "sku_version", "rate_card_ref", "plan_id", "subscription_id", "plan_version", "quantity", "quantity_unit", "pricing_basis", "requested_discount", "feature_overrides"]

    @field_validator('pricing_basis')
    def pricing_basis_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['recurring', 'one_time', 'usage_estimate']):
            raise ValueError("must be one of enum values ('recurring', 'one_time', 'usage_estimate')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QuoteLineItemInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QuoteLineItemInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "line_no": obj.get("line_no"),
            "sku_ref": obj.get("sku_ref"),
            "feature_key": obj.get("feature_key"),
            "sku_version": obj.get("sku_version"),
            "rate_card_ref": obj.get("rate_card_ref"),
            "plan_id": obj.get("plan_id"),
            "subscription_id": obj.get("subscription_id"),
            "plan_version": obj.get("plan_version"),
            "quantity": obj.get("quantity") if obj.get("quantity") is not None else '1',
            "quantity_unit": obj.get("quantity_unit") if obj.get("quantity_unit") is not None else 'unit',
            "pricing_basis": obj.get("pricing_basis") if obj.get("pricing_basis") is not None else 'recurring',
            "requested_discount": obj.get("requested_discount"),
            "feature_overrides": obj.get("feature_overrides")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


