# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0-rc2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class RecordUsageRequest(BaseModel):
    """
    Request to record usage event.
    """ # noqa: E501
    tenant_id: StrictStr = Field(description="Tenant identifier")
    subject_id: Annotated[str, Field(min_length=1, strict=True, max_length=255)] = Field(description="Subject identifier")
    pool_id: StrictStr = Field(description="Credit pool identifier")
    wallet_id: Optional[StrictStr] = None
    subscription_id: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    feature_key: Annotated[str, Field(min_length=1, strict=True, max_length=255)] = Field(description="Feature key")
    meter_slug: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    usage_event_id: Annotated[str, Field(min_length=1, strict=True, max_length=255)] = Field(description="Usage event ID (idempotency key)")
    request_id: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    job_id: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    effective_at: datetime = Field(description="Effective timestamp")
    usage_vector: Dict[str, Any] = Field(description="Usage vector (JSON object)")
    __properties: ClassVar[List[str]] = ["tenant_id", "subject_id", "pool_id", "wallet_id", "subscription_id", "feature_key", "meter_slug", "usage_event_id", "request_id", "job_id", "effective_at", "usage_vector"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RecordUsageRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if wallet_id (nullable) is None
        # and model_fields_set contains the field
        if self.wallet_id is None and "wallet_id" in self.model_fields_set:
            _dict['wallet_id'] = None

        # set to None if subscription_id (nullable) is None
        # and model_fields_set contains the field
        if self.subscription_id is None and "subscription_id" in self.model_fields_set:
            _dict['subscription_id'] = None

        # set to None if meter_slug (nullable) is None
        # and model_fields_set contains the field
        if self.meter_slug is None and "meter_slug" in self.model_fields_set:
            _dict['meter_slug'] = None

        # set to None if request_id (nullable) is None
        # and model_fields_set contains the field
        if self.request_id is None and "request_id" in self.model_fields_set:
            _dict['request_id'] = None

        # set to None if job_id (nullable) is None
        # and model_fields_set contains the field
        if self.job_id is None and "job_id" in self.model_fields_set:
            _dict['job_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RecordUsageRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tenant_id": obj.get("tenant_id"),
            "subject_id": obj.get("subject_id"),
            "pool_id": obj.get("pool_id"),
            "wallet_id": obj.get("wallet_id"),
            "subscription_id": obj.get("subscription_id"),
            "feature_key": obj.get("feature_key"),
            "meter_slug": obj.get("meter_slug"),
            "usage_event_id": obj.get("usage_event_id"),
            "request_id": obj.get("request_id"),
            "job_id": obj.get("job_id"),
            "effective_at": obj.get("effective_at"),
            "usage_vector": obj.get("usage_vector")
        })
        return _obj


