# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.2.0-rc5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from moolabs.models.reconciliation_basis_out import ReconciliationBasisOut
from typing import Optional, Set
from typing_extensions import Self

class SimulateMarginResponse(BaseModel):
    """
    SimulateMarginResponse
    """ # noqa: E501
    feature_key: StrictStr
    simulation_period_months: StrictInt
    projected_volume: StrictInt
    proposed_price_per_event: Union[StrictFloat, StrictInt]
    projected_revenue: Union[StrictFloat, StrictInt]
    projected_cost: Union[StrictFloat, StrictInt]
    projected_margin: Union[StrictFloat, StrictInt]
    projected_margin_pct: Union[StrictFloat, StrictInt]
    bom_id: StrictStr
    bom_version: StrictInt
    component_breakdown: List[Dict[str, Any]]
    risk_flags: List[Dict[str, Any]]
    reconciliation_basis: ReconciliationBasisOut
    __properties: ClassVar[List[str]] = ["feature_key", "simulation_period_months", "projected_volume", "proposed_price_per_event", "projected_revenue", "projected_cost", "projected_margin", "projected_margin_pct", "bom_id", "bom_version", "component_breakdown", "risk_flags", "reconciliation_basis"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SimulateMarginResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of reconciliation_basis
        if self.reconciliation_basis:
            _dict['reconciliation_basis'] = self.reconciliation_basis.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SimulateMarginResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "feature_key": obj.get("feature_key"),
            "simulation_period_months": obj.get("simulation_period_months"),
            "projected_volume": obj.get("projected_volume"),
            "proposed_price_per_event": obj.get("proposed_price_per_event"),
            "projected_revenue": obj.get("projected_revenue"),
            "projected_cost": obj.get("projected_cost"),
            "projected_margin": obj.get("projected_margin"),
            "projected_margin_pct": obj.get("projected_margin_pct"),
            "bom_id": obj.get("bom_id"),
            "bom_version": obj.get("bom_version"),
            "component_breakdown": obj.get("component_breakdown"),
            "risk_flags": obj.get("risk_flags"),
            "reconciliation_basis": ReconciliationBasisOut.from_dict(obj["reconciliation_basis"]) if obj.get("reconciliation_basis") is not None else None
        })
        return _obj


