# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0-rc7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from moolabs.models.subscription_edit_operation import SubscriptionEditOperation
from moolabs.models.subscription_timing import SubscriptionTiming
from typing import Optional, Set
from typing_extensions import Self

class SubscriptionEdit(BaseModel):
    """
    Subscription edit input.
    """ # noqa: E501
    customizations: Annotated[List[SubscriptionEditOperation], Field(max_length=100)] = Field(description="Batch processing commands for manipulating running subscriptions. The key format is `/phases/{phaseKey}` or `/phases/{phaseKey}/items/{itemKey}`.")
    timing: Optional[SubscriptionTiming] = Field(default=None, description="Whether the billing period should be restarted.Timing configuration to allow for the changes to take effect at different times.")
    __properties: ClassVar[List[str]] = ["customizations", "timing"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubscriptionEdit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in customizations (list)
        _items = []
        if self.customizations:
            for _item_customizations in self.customizations:
                if _item_customizations:
                    _items.append(_item_customizations.to_dict())
            _dict['customizations'] = _items
        # override the default output from pydantic by calling `to_dict()` of timing
        if self.timing:
            _dict['timing'] = self.timing.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubscriptionEdit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "customizations": [SubscriptionEditOperation.from_dict(_item) for _item in obj["customizations"]] if obj.get("customizations") is not None else None,
            "timing": SubscriptionTiming.from_dict(obj["timing"]) if obj.get("timing") is not None else None
        })
        return _obj


