# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from moolabs.models.subscription_error_extensions import SubscriptionErrorExtensions
from typing import Optional, Set
from typing_extensions import Self

class SubscriptionConflictErrorResponse(BaseModel):
    """
    The request could not be completed due to a conflict with the current state of the target resource. Variants with ErrorExtensions specific to subscriptions.
    """ # noqa: E501
    type: StrictStr = Field(description="Type contains a URI that identifies the problem type.")
    title: StrictStr = Field(description="A a short, human-readable summary of the problem type.")
    status: Optional[Annotated[int, Field(le=599, strict=True, ge=400)]] = Field(default=None, description="The HTTP status code generated by the origin server for this occurrence of the problem.")
    detail: StrictStr = Field(description="A human-readable explanation specific to this occurrence of the problem.")
    instance: StrictStr = Field(description="A URI reference that identifies the specific occurrence of the problem.")
    extensions: Optional[SubscriptionErrorExtensions] = Field(default=None, description="Additional properties specific to the problem type may be present.")
    __properties: ClassVar[List[str]] = ["type", "title", "status", "detail", "instance", "extensions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubscriptionConflictErrorResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of extensions
        if self.extensions:
            _dict['extensions'] = self.extensions.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubscriptionConflictErrorResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type") if obj.get("type") is not None else 'about:blank',
            "title": obj.get("title"),
            "status": obj.get("status"),
            "detail": obj.get("detail"),
            "instance": obj.get("instance"),
            "extensions": SubscriptionErrorExtensions.from_dict(obj["extensions"]) if obj.get("extensions") is not None else None
        })
        return _obj


