# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

    The version of the OpenAPI document: 0.0.0-rc7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from moolabs.models.discounts import Discounts
from typing import Optional, Set
from typing_extensions import Self

class SubscriptionPhase(BaseModel):
    """
    Subscription phase, analogous to plan phases.
    """ # noqa: E501
    id: Annotated[str, Field(strict=True)] = Field(description="A unique identifier for the resource.")
    name: Annotated[str, Field(min_length=1, strict=True, max_length=256)] = Field(description="Human-readable name for the resource. Between 1 and 256 characters.")
    description: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = Field(default=None, description="Optional description of the resource. Maximum 1024 characters.")
    metadata: Optional[Dict[str, StrictStr]] = Field(default=None, description="Additional metadata for the resource.")
    created_at: datetime = Field(description="Timestamp of when the resource was created.", alias="createdAt")
    updated_at: datetime = Field(description="Timestamp of when the resource was last updated.", alias="updatedAt")
    deleted_at: Optional[datetime] = Field(default=None, description="Timestamp of when the resource was permanently deleted.", alias="deletedAt")
    key: Annotated[str, Field(min_length=1, strict=True, max_length=64)] = Field(description="A locally unique identifier for the resource.")
    discounts: Optional[Discounts] = Field(default=None, description="The discounts on the plan.")
    active_from: datetime = Field(description="The time from which the phase is active.", alias="activeFrom")
    active_to: Optional[datetime] = Field(default=None, description="The until which the Phase is active.", alias="activeTo")
    __properties: ClassVar[List[str]] = ["id", "name", "description", "metadata", "createdAt", "updatedAt", "deletedAt", "key", "discounts", "activeFrom", "activeTo"]

    @field_validator('id')
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[0-7][0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{25}$", value):
            raise ValueError(r"must validate the regular expression /^[0-7][0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{25}$/")
        return value

    @field_validator('key')
    def key_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-z0-9]+(?:_[a-z0-9]+)*$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9]+(?:_[a-z0-9]+)*$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubscriptionPhase from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "created_at",
            "updated_at",
            "deleted_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of discounts
        if self.discounts:
            _dict['discounts'] = self.discounts.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubscriptionPhase from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "metadata": obj.get("metadata"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "deletedAt": obj.get("deletedAt"),
            "key": obj.get("key"),
            "discounts": Discounts.from_dict(obj["discounts"]) if obj.get("discounts") is not None else None,
            "activeFrom": obj.get("activeFrom"),
            "activeTo": obj.get("activeTo")
        })
        return _obj


