# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TemplateVersionResponse(BaseModel):
    """
    TemplateVersionResponse
    """ # noqa: E501
    id: StrictStr
    canonical_template_key: StrictStr
    channel: Optional[StrictStr] = 'email'
    version: StrictInt
    status: StrictStr
    draft_group_id: Optional[StrictStr] = None
    draft_state: Optional[StrictStr] = None
    stale_reason: Optional[StrictStr] = None
    base_published_version_id: Optional[StrictStr] = None
    subject_template: StrictStr
    body_template: StrictStr
    content_hash: StrictStr
    validation_snapshot: Dict[str, Any]
    disclosure_policy_hash: StrictStr
    provider_readiness_hash: StrictStr
    payment_instructions_hash: StrictStr
    created_by_actor_id: StrictStr
    created_by_actor_display: Optional[StrictStr] = None
    published_by_actor_id: Optional[StrictStr] = None
    published_at: Optional[StrictStr] = None
    locked: Optional[StrictBool] = False
    lock_owner_actor_id: Optional[StrictStr] = None
    lock_owner_display: Optional[StrictStr] = None
    lock_expires_at: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "canonical_template_key", "channel", "version", "status", "draft_group_id", "draft_state", "stale_reason", "base_published_version_id", "subject_template", "body_template", "content_hash", "validation_snapshot", "disclosure_policy_hash", "provider_readiness_hash", "payment_instructions_hash", "created_by_actor_id", "created_by_actor_display", "published_by_actor_id", "published_at", "locked", "lock_owner_actor_id", "lock_owner_display", "lock_expires_at"]

    @field_validator('channel')
    def channel_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['email']):
            raise ValueError("must be one of enum values ('email')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TemplateVersionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TemplateVersionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "canonical_template_key": obj.get("canonical_template_key"),
            "channel": obj.get("channel") if obj.get("channel") is not None else 'email',
            "version": obj.get("version"),
            "status": obj.get("status"),
            "draft_group_id": obj.get("draft_group_id"),
            "draft_state": obj.get("draft_state"),
            "stale_reason": obj.get("stale_reason"),
            "base_published_version_id": obj.get("base_published_version_id"),
            "subject_template": obj.get("subject_template"),
            "body_template": obj.get("body_template"),
            "content_hash": obj.get("content_hash"),
            "validation_snapshot": obj.get("validation_snapshot"),
            "disclosure_policy_hash": obj.get("disclosure_policy_hash"),
            "provider_readiness_hash": obj.get("provider_readiness_hash"),
            "payment_instructions_hash": obj.get("payment_instructions_hash"),
            "created_by_actor_id": obj.get("created_by_actor_id"),
            "created_by_actor_display": obj.get("created_by_actor_display"),
            "published_by_actor_id": obj.get("published_by_actor_id"),
            "published_at": obj.get("published_at"),
            "locked": obj.get("locked") if obj.get("locked") is not None else False,
            "lock_owner_actor_id": obj.get("lock_owner_actor_id"),
            "lock_owner_display": obj.get("lock_owner_display"),
            "lock_expires_at": obj.get("lock_expires_at")
        })
        return _obj


