# coding: utf-8

"""
    Moolabs API

    Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

    The version of the OpenAPI document: 0.3.0-rc2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated
from moolabs.models.approval_action_request import ApprovalActionRequest
from moolabs.models.approval_action_response import ApprovalActionResponse
from moolabs.models.communication_create import CommunicationCreate
from moolabs.models.communication_list_response import CommunicationListResponse
from moolabs.models.communication_response import CommunicationResponse
from moolabs.models.provider_confirmation_repair_request import ProviderConfirmationRepairRequest

from moolabs.api_client import ApiClient, RequestSerialized
from moolabs.api_response import ApiResponse
from moolabs.rest import RESTResponseType


class ArcCommunicationsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def approve_communication(
        self,
        case_id: StrictStr,
        comm_id: StrictStr,
        x_api_key: Optional[StrictStr] = None,
        x_tenant_id: Optional[StrictStr] = None,
        x_org_id: Optional[StrictStr] = None,
        authorization: Optional[StrictStr] = None,
        approval_action_request: Optional[ApprovalActionRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApprovalActionResponse:
        """Approve Communication

        Approve and send a draft communication.

        :param case_id: (required)
        :type case_id: str
        :param comm_id: (required)
        :type comm_id: str
        :param x_api_key:
        :type x_api_key: str
        :param x_tenant_id:
        :type x_tenant_id: str
        :param x_org_id:
        :type x_org_id: str
        :param authorization:
        :type authorization: str
        :param approval_action_request:
        :type approval_action_request: ApprovalActionRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._approve_communication_serialize(
            case_id=case_id,
            comm_id=comm_id,
            x_api_key=x_api_key,
            x_tenant_id=x_tenant_id,
            x_org_id=x_org_id,
            authorization=authorization,
            approval_action_request=approval_action_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ApprovalActionResponse",
            '422': "ArcHTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def approve_communication_with_http_info(
        self,
        case_id: StrictStr,
        comm_id: StrictStr,
        x_api_key: Optional[StrictStr] = None,
        x_tenant_id: Optional[StrictStr] = None,
        x_org_id: Optional[StrictStr] = None,
        authorization: Optional[StrictStr] = None,
        approval_action_request: Optional[ApprovalActionRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ApprovalActionResponse]:
        """Approve Communication

        Approve and send a draft communication.

        :param case_id: (required)
        :type case_id: str
        :param comm_id: (required)
        :type comm_id: str
        :param x_api_key:
        :type x_api_key: str
        :param x_tenant_id:
        :type x_tenant_id: str
        :param x_org_id:
        :type x_org_id: str
        :param authorization:
        :type authorization: str
        :param approval_action_request:
        :type approval_action_request: ApprovalActionRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._approve_communication_serialize(
            case_id=case_id,
            comm_id=comm_id,
            x_api_key=x_api_key,
            x_tenant_id=x_tenant_id,
            x_org_id=x_org_id,
            authorization=authorization,
            approval_action_request=approval_action_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ApprovalActionResponse",
            '422': "ArcHTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def approve_communication_without_preload_content(
        self,
        case_id: StrictStr,
        comm_id: StrictStr,
        x_api_key: Optional[StrictStr] = None,
        x_tenant_id: Optional[StrictStr] = None,
        x_org_id: Optional[StrictStr] = None,
        authorization: Optional[StrictStr] = None,
        approval_action_request: Optional[ApprovalActionRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Approve Communication

        Approve and send a draft communication.

        :param case_id: (required)
        :type case_id: str
        :param comm_id: (required)
        :type comm_id: str
        :param x_api_key:
        :type x_api_key: str
        :param x_tenant_id:
        :type x_tenant_id: str
        :param x_org_id:
        :type x_org_id: str
        :param authorization:
        :type authorization: str
        :param approval_action_request:
        :type approval_action_request: ApprovalActionRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._approve_communication_serialize(
            case_id=case_id,
            comm_id=comm_id,
            x_api_key=x_api_key,
            x_tenant_id=x_tenant_id,
            x_org_id=x_org_id,
            authorization=authorization,
            approval_action_request=approval_action_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ApprovalActionResponse",
            '422': "ArcHTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _approve_communication_serialize(
        self,
        case_id,
        comm_id,
        x_api_key,
        x_tenant_id,
        x_org_id,
        authorization,
        approval_action_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if case_id is not None:
            _path_params['case_id'] = case_id
        if comm_id is not None:
            _path_params['comm_id'] = comm_id
        # process the query parameters
        # process the header parameters
        if x_api_key is not None:
            _header_params['X-API-Key'] = x_api_key
        if x_tenant_id is not None:
            _header_params['X-Tenant-Id'] = x_tenant_id
        if x_org_id is not None:
            _header_params['X-Org-Id'] = x_org_id
        if authorization is not None:
            _header_params['Authorization'] = authorization
        # process the form parameters
        # process the body parameter
        if approval_action_request is not None:
            _body_params = approval_action_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/v1/arc/cases/{case_id}/communications/{comm_id}/approve',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def create_communication(
        self,
        case_id: StrictStr,
        communication_create: CommunicationCreate,
        x_api_key: Optional[StrictStr] = None,
        x_tenant_id: Optional[StrictStr] = None,
        x_org_id: Optional[StrictStr] = None,
        authorization: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CommunicationResponse:
        """Create Communication

        Create a communication for a case.

        :param case_id: (required)
        :type case_id: str
        :param communication_create: (required)
        :type communication_create: CommunicationCreate
        :param x_api_key:
        :type x_api_key: str
        :param x_tenant_id:
        :type x_tenant_id: str
        :param x_org_id:
        :type x_org_id: str
        :param authorization:
        :type authorization: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_communication_serialize(
            case_id=case_id,
            communication_create=communication_create,
            x_api_key=x_api_key,
            x_tenant_id=x_tenant_id,
            x_org_id=x_org_id,
            authorization=authorization,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "CommunicationResponse",
            '422': "ArcHTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def create_communication_with_http_info(
        self,
        case_id: StrictStr,
        communication_create: CommunicationCreate,
        x_api_key: Optional[StrictStr] = None,
        x_tenant_id: Optional[StrictStr] = None,
        x_org_id: Optional[StrictStr] = None,
        authorization: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[CommunicationResponse]:
        """Create Communication

        Create a communication for a case.

        :param case_id: (required)
        :type case_id: str
        :param communication_create: (required)
        :type communication_create: CommunicationCreate
        :param x_api_key:
        :type x_api_key: str
        :param x_tenant_id:
        :type x_tenant_id: str
        :param x_org_id:
        :type x_org_id: str
        :param authorization:
        :type authorization: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_communication_serialize(
            case_id=case_id,
            communication_create=communication_create,
            x_api_key=x_api_key,
            x_tenant_id=x_tenant_id,
            x_org_id=x_org_id,
            authorization=authorization,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "CommunicationResponse",
            '422': "ArcHTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def create_communication_without_preload_content(
        self,
        case_id: StrictStr,
        communication_create: CommunicationCreate,
        x_api_key: Optional[StrictStr] = None,
        x_tenant_id: Optional[StrictStr] = None,
        x_org_id: Optional[StrictStr] = None,
        authorization: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Create Communication

        Create a communication for a case.

        :param case_id: (required)
        :type case_id: str
        :param communication_create: (required)
        :type communication_create: CommunicationCreate
        :param x_api_key:
        :type x_api_key: str
        :param x_tenant_id:
        :type x_tenant_id: str
        :param x_org_id:
        :type x_org_id: str
        :param authorization:
        :type authorization: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_communication_serialize(
            case_id=case_id,
            communication_create=communication_create,
            x_api_key=x_api_key,
            x_tenant_id=x_tenant_id,
            x_org_id=x_org_id,
            authorization=authorization,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "CommunicationResponse",
            '422': "ArcHTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _create_communication_serialize(
        self,
        case_id,
        communication_create,
        x_api_key,
        x_tenant_id,
        x_org_id,
        authorization,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if case_id is not None:
            _path_params['case_id'] = case_id
        # process the query parameters
        # process the header parameters
        if x_api_key is not None:
            _header_params['X-API-Key'] = x_api_key
        if x_tenant_id is not None:
            _header_params['X-Tenant-Id'] = x_tenant_id
        if x_org_id is not None:
            _header_params['X-Org-Id'] = x_org_id
        if authorization is not None:
            _header_params['Authorization'] = authorization
        # process the form parameters
        # process the body parameter
        if communication_create is not None:
            _body_params = communication_create


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/v1/arc/cases/{case_id}/communications',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def list_communications(
        self,
        case_id: StrictStr,
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        page_size: Optional[Annotated[int, Field(le=200, strict=True, ge=1)]] = None,
        direction: Optional[StrictStr] = None,
        channel: Optional[StrictStr] = None,
        status: Optional[StrictStr] = None,
        x_api_key: Optional[StrictStr] = None,
        x_tenant_id: Optional[StrictStr] = None,
        x_org_id: Optional[StrictStr] = None,
        authorization: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CommunicationListResponse:
        """List Communications

        List communications for a case.

        :param case_id: (required)
        :type case_id: str
        :param page:
        :type page: int
        :param page_size:
        :type page_size: int
        :param direction:
        :type direction: str
        :param channel:
        :type channel: str
        :param status:
        :type status: str
        :param x_api_key:
        :type x_api_key: str
        :param x_tenant_id:
        :type x_tenant_id: str
        :param x_org_id:
        :type x_org_id: str
        :param authorization:
        :type authorization: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_communications_serialize(
            case_id=case_id,
            page=page,
            page_size=page_size,
            direction=direction,
            channel=channel,
            status=status,
            x_api_key=x_api_key,
            x_tenant_id=x_tenant_id,
            x_org_id=x_org_id,
            authorization=authorization,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CommunicationListResponse",
            '422': "ArcHTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_communications_with_http_info(
        self,
        case_id: StrictStr,
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        page_size: Optional[Annotated[int, Field(le=200, strict=True, ge=1)]] = None,
        direction: Optional[StrictStr] = None,
        channel: Optional[StrictStr] = None,
        status: Optional[StrictStr] = None,
        x_api_key: Optional[StrictStr] = None,
        x_tenant_id: Optional[StrictStr] = None,
        x_org_id: Optional[StrictStr] = None,
        authorization: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[CommunicationListResponse]:
        """List Communications

        List communications for a case.

        :param case_id: (required)
        :type case_id: str
        :param page:
        :type page: int
        :param page_size:
        :type page_size: int
        :param direction:
        :type direction: str
        :param channel:
        :type channel: str
        :param status:
        :type status: str
        :param x_api_key:
        :type x_api_key: str
        :param x_tenant_id:
        :type x_tenant_id: str
        :param x_org_id:
        :type x_org_id: str
        :param authorization:
        :type authorization: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_communications_serialize(
            case_id=case_id,
            page=page,
            page_size=page_size,
            direction=direction,
            channel=channel,
            status=status,
            x_api_key=x_api_key,
            x_tenant_id=x_tenant_id,
            x_org_id=x_org_id,
            authorization=authorization,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CommunicationListResponse",
            '422': "ArcHTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_communications_without_preload_content(
        self,
        case_id: StrictStr,
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        page_size: Optional[Annotated[int, Field(le=200, strict=True, ge=1)]] = None,
        direction: Optional[StrictStr] = None,
        channel: Optional[StrictStr] = None,
        status: Optional[StrictStr] = None,
        x_api_key: Optional[StrictStr] = None,
        x_tenant_id: Optional[StrictStr] = None,
        x_org_id: Optional[StrictStr] = None,
        authorization: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List Communications

        List communications for a case.

        :param case_id: (required)
        :type case_id: str
        :param page:
        :type page: int
        :param page_size:
        :type page_size: int
        :param direction:
        :type direction: str
        :param channel:
        :type channel: str
        :param status:
        :type status: str
        :param x_api_key:
        :type x_api_key: str
        :param x_tenant_id:
        :type x_tenant_id: str
        :param x_org_id:
        :type x_org_id: str
        :param authorization:
        :type authorization: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_communications_serialize(
            case_id=case_id,
            page=page,
            page_size=page_size,
            direction=direction,
            channel=channel,
            status=status,
            x_api_key=x_api_key,
            x_tenant_id=x_tenant_id,
            x_org_id=x_org_id,
            authorization=authorization,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CommunicationListResponse",
            '422': "ArcHTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_communications_serialize(
        self,
        case_id,
        page,
        page_size,
        direction,
        channel,
        status,
        x_api_key,
        x_tenant_id,
        x_org_id,
        authorization,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if case_id is not None:
            _path_params['case_id'] = case_id
        # process the query parameters
        if page is not None:
            
            _query_params.append(('page', page))
            
        if page_size is not None:
            
            _query_params.append(('page_size', page_size))
            
        if direction is not None:
            
            _query_params.append(('direction', direction))
            
        if channel is not None:
            
            _query_params.append(('channel', channel))
            
        if status is not None:
            
            _query_params.append(('status', status))
            
        # process the header parameters
        if x_api_key is not None:
            _header_params['X-API-Key'] = x_api_key
        if x_tenant_id is not None:
            _header_params['X-Tenant-Id'] = x_tenant_id
        if x_org_id is not None:
            _header_params['X-Org-Id'] = x_org_id
        if authorization is not None:
            _header_params['Authorization'] = authorization
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/arc/cases/{case_id}/communications',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def reject_communication(
        self,
        case_id: StrictStr,
        comm_id: StrictStr,
        x_api_key: Optional[StrictStr] = None,
        x_tenant_id: Optional[StrictStr] = None,
        x_org_id: Optional[StrictStr] = None,
        authorization: Optional[StrictStr] = None,
        x_acting_user: Optional[StrictStr] = None,
        x_user_id: Optional[StrictStr] = None,
        x_arc_proxy_secret: Optional[StrictStr] = None,
        approval_action_request: Optional[ApprovalActionRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApprovalActionResponse:
        """Reject Communication

        Reject a draft communication.

        :param case_id: (required)
        :type case_id: str
        :param comm_id: (required)
        :type comm_id: str
        :param x_api_key:
        :type x_api_key: str
        :param x_tenant_id:
        :type x_tenant_id: str
        :param x_org_id:
        :type x_org_id: str
        :param authorization:
        :type authorization: str
        :param x_acting_user:
        :type x_acting_user: str
        :param x_user_id:
        :type x_user_id: str
        :param x_arc_proxy_secret:
        :type x_arc_proxy_secret: str
        :param approval_action_request:
        :type approval_action_request: ApprovalActionRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._reject_communication_serialize(
            case_id=case_id,
            comm_id=comm_id,
            x_api_key=x_api_key,
            x_tenant_id=x_tenant_id,
            x_org_id=x_org_id,
            authorization=authorization,
            x_acting_user=x_acting_user,
            x_user_id=x_user_id,
            x_arc_proxy_secret=x_arc_proxy_secret,
            approval_action_request=approval_action_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ApprovalActionResponse",
            '422': "ArcHTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def reject_communication_with_http_info(
        self,
        case_id: StrictStr,
        comm_id: StrictStr,
        x_api_key: Optional[StrictStr] = None,
        x_tenant_id: Optional[StrictStr] = None,
        x_org_id: Optional[StrictStr] = None,
        authorization: Optional[StrictStr] = None,
        x_acting_user: Optional[StrictStr] = None,
        x_user_id: Optional[StrictStr] = None,
        x_arc_proxy_secret: Optional[StrictStr] = None,
        approval_action_request: Optional[ApprovalActionRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ApprovalActionResponse]:
        """Reject Communication

        Reject a draft communication.

        :param case_id: (required)
        :type case_id: str
        :param comm_id: (required)
        :type comm_id: str
        :param x_api_key:
        :type x_api_key: str
        :param x_tenant_id:
        :type x_tenant_id: str
        :param x_org_id:
        :type x_org_id: str
        :param authorization:
        :type authorization: str
        :param x_acting_user:
        :type x_acting_user: str
        :param x_user_id:
        :type x_user_id: str
        :param x_arc_proxy_secret:
        :type x_arc_proxy_secret: str
        :param approval_action_request:
        :type approval_action_request: ApprovalActionRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._reject_communication_serialize(
            case_id=case_id,
            comm_id=comm_id,
            x_api_key=x_api_key,
            x_tenant_id=x_tenant_id,
            x_org_id=x_org_id,
            authorization=authorization,
            x_acting_user=x_acting_user,
            x_user_id=x_user_id,
            x_arc_proxy_secret=x_arc_proxy_secret,
            approval_action_request=approval_action_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ApprovalActionResponse",
            '422': "ArcHTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def reject_communication_without_preload_content(
        self,
        case_id: StrictStr,
        comm_id: StrictStr,
        x_api_key: Optional[StrictStr] = None,
        x_tenant_id: Optional[StrictStr] = None,
        x_org_id: Optional[StrictStr] = None,
        authorization: Optional[StrictStr] = None,
        x_acting_user: Optional[StrictStr] = None,
        x_user_id: Optional[StrictStr] = None,
        x_arc_proxy_secret: Optional[StrictStr] = None,
        approval_action_request: Optional[ApprovalActionRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Reject Communication

        Reject a draft communication.

        :param case_id: (required)
        :type case_id: str
        :param comm_id: (required)
        :type comm_id: str
        :param x_api_key:
        :type x_api_key: str
        :param x_tenant_id:
        :type x_tenant_id: str
        :param x_org_id:
        :type x_org_id: str
        :param authorization:
        :type authorization: str
        :param x_acting_user:
        :type x_acting_user: str
        :param x_user_id:
        :type x_user_id: str
        :param x_arc_proxy_secret:
        :type x_arc_proxy_secret: str
        :param approval_action_request:
        :type approval_action_request: ApprovalActionRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._reject_communication_serialize(
            case_id=case_id,
            comm_id=comm_id,
            x_api_key=x_api_key,
            x_tenant_id=x_tenant_id,
            x_org_id=x_org_id,
            authorization=authorization,
            x_acting_user=x_acting_user,
            x_user_id=x_user_id,
            x_arc_proxy_secret=x_arc_proxy_secret,
            approval_action_request=approval_action_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ApprovalActionResponse",
            '422': "ArcHTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _reject_communication_serialize(
        self,
        case_id,
        comm_id,
        x_api_key,
        x_tenant_id,
        x_org_id,
        authorization,
        x_acting_user,
        x_user_id,
        x_arc_proxy_secret,
        approval_action_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if case_id is not None:
            _path_params['case_id'] = case_id
        if comm_id is not None:
            _path_params['comm_id'] = comm_id
        # process the query parameters
        # process the header parameters
        if x_api_key is not None:
            _header_params['X-API-Key'] = x_api_key
        if x_tenant_id is not None:
            _header_params['X-Tenant-Id'] = x_tenant_id
        if x_org_id is not None:
            _header_params['X-Org-Id'] = x_org_id
        if authorization is not None:
            _header_params['Authorization'] = authorization
        if x_acting_user is not None:
            _header_params['X-Acting-User'] = x_acting_user
        if x_user_id is not None:
            _header_params['X-User-Id'] = x_user_id
        if x_arc_proxy_secret is not None:
            _header_params['X-Arc-Proxy-Secret'] = x_arc_proxy_secret
        # process the form parameters
        # process the body parameter
        if approval_action_request is not None:
            _body_params = approval_action_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/v1/arc/cases/{case_id}/communications/{comm_id}/reject',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def resolve_provider_confirmation_v1_arc(
        self,
        case_id: StrictStr,
        comm_id: StrictStr,
        provider_confirmation_repair_request: ProviderConfirmationRepairRequest,
        x_api_key: Optional[StrictStr] = None,
        x_tenant_id: Optional[StrictStr] = None,
        x_org_id: Optional[StrictStr] = None,
        authorization: Optional[StrictStr] = None,
        x_user_id: Optional[StrictStr] = None,
        x_arc_roles: Optional[StrictStr] = None,
        x_arc_proxy_secret: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApprovalActionResponse:
        """Resolve Provider Confirmation

        Operator repair for a communication with unknown provider outcome.

        :param case_id: (required)
        :type case_id: str
        :param comm_id: (required)
        :type comm_id: str
        :param provider_confirmation_repair_request: (required)
        :type provider_confirmation_repair_request: ProviderConfirmationRepairRequest
        :param x_api_key:
        :type x_api_key: str
        :param x_tenant_id:
        :type x_tenant_id: str
        :param x_org_id:
        :type x_org_id: str
        :param authorization:
        :type authorization: str
        :param x_user_id:
        :type x_user_id: str
        :param x_arc_roles:
        :type x_arc_roles: str
        :param x_arc_proxy_secret:
        :type x_arc_proxy_secret: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._resolve_provider_confirmation_v1_arc_serialize(
            case_id=case_id,
            comm_id=comm_id,
            provider_confirmation_repair_request=provider_confirmation_repair_request,
            x_api_key=x_api_key,
            x_tenant_id=x_tenant_id,
            x_org_id=x_org_id,
            authorization=authorization,
            x_user_id=x_user_id,
            x_arc_roles=x_arc_roles,
            x_arc_proxy_secret=x_arc_proxy_secret,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ApprovalActionResponse",
            '422': "ArcHTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def resolve_provider_confirmation_v1_arc_with_http_info(
        self,
        case_id: StrictStr,
        comm_id: StrictStr,
        provider_confirmation_repair_request: ProviderConfirmationRepairRequest,
        x_api_key: Optional[StrictStr] = None,
        x_tenant_id: Optional[StrictStr] = None,
        x_org_id: Optional[StrictStr] = None,
        authorization: Optional[StrictStr] = None,
        x_user_id: Optional[StrictStr] = None,
        x_arc_roles: Optional[StrictStr] = None,
        x_arc_proxy_secret: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ApprovalActionResponse]:
        """Resolve Provider Confirmation

        Operator repair for a communication with unknown provider outcome.

        :param case_id: (required)
        :type case_id: str
        :param comm_id: (required)
        :type comm_id: str
        :param provider_confirmation_repair_request: (required)
        :type provider_confirmation_repair_request: ProviderConfirmationRepairRequest
        :param x_api_key:
        :type x_api_key: str
        :param x_tenant_id:
        :type x_tenant_id: str
        :param x_org_id:
        :type x_org_id: str
        :param authorization:
        :type authorization: str
        :param x_user_id:
        :type x_user_id: str
        :param x_arc_roles:
        :type x_arc_roles: str
        :param x_arc_proxy_secret:
        :type x_arc_proxy_secret: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._resolve_provider_confirmation_v1_arc_serialize(
            case_id=case_id,
            comm_id=comm_id,
            provider_confirmation_repair_request=provider_confirmation_repair_request,
            x_api_key=x_api_key,
            x_tenant_id=x_tenant_id,
            x_org_id=x_org_id,
            authorization=authorization,
            x_user_id=x_user_id,
            x_arc_roles=x_arc_roles,
            x_arc_proxy_secret=x_arc_proxy_secret,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ApprovalActionResponse",
            '422': "ArcHTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def resolve_provider_confirmation_v1_arc_without_preload_content(
        self,
        case_id: StrictStr,
        comm_id: StrictStr,
        provider_confirmation_repair_request: ProviderConfirmationRepairRequest,
        x_api_key: Optional[StrictStr] = None,
        x_tenant_id: Optional[StrictStr] = None,
        x_org_id: Optional[StrictStr] = None,
        authorization: Optional[StrictStr] = None,
        x_user_id: Optional[StrictStr] = None,
        x_arc_roles: Optional[StrictStr] = None,
        x_arc_proxy_secret: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Resolve Provider Confirmation

        Operator repair for a communication with unknown provider outcome.

        :param case_id: (required)
        :type case_id: str
        :param comm_id: (required)
        :type comm_id: str
        :param provider_confirmation_repair_request: (required)
        :type provider_confirmation_repair_request: ProviderConfirmationRepairRequest
        :param x_api_key:
        :type x_api_key: str
        :param x_tenant_id:
        :type x_tenant_id: str
        :param x_org_id:
        :type x_org_id: str
        :param authorization:
        :type authorization: str
        :param x_user_id:
        :type x_user_id: str
        :param x_arc_roles:
        :type x_arc_roles: str
        :param x_arc_proxy_secret:
        :type x_arc_proxy_secret: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._resolve_provider_confirmation_v1_arc_serialize(
            case_id=case_id,
            comm_id=comm_id,
            provider_confirmation_repair_request=provider_confirmation_repair_request,
            x_api_key=x_api_key,
            x_tenant_id=x_tenant_id,
            x_org_id=x_org_id,
            authorization=authorization,
            x_user_id=x_user_id,
            x_arc_roles=x_arc_roles,
            x_arc_proxy_secret=x_arc_proxy_secret,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ApprovalActionResponse",
            '422': "ArcHTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _resolve_provider_confirmation_v1_arc_serialize(
        self,
        case_id,
        comm_id,
        provider_confirmation_repair_request,
        x_api_key,
        x_tenant_id,
        x_org_id,
        authorization,
        x_user_id,
        x_arc_roles,
        x_arc_proxy_secret,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if case_id is not None:
            _path_params['case_id'] = case_id
        if comm_id is not None:
            _path_params['comm_id'] = comm_id
        # process the query parameters
        # process the header parameters
        if x_api_key is not None:
            _header_params['X-API-Key'] = x_api_key
        if x_tenant_id is not None:
            _header_params['X-Tenant-Id'] = x_tenant_id
        if x_org_id is not None:
            _header_params['X-Org-Id'] = x_org_id
        if authorization is not None:
            _header_params['Authorization'] = authorization
        if x_user_id is not None:
            _header_params['X-User-Id'] = x_user_id
        if x_arc_roles is not None:
            _header_params['X-Arc-Roles'] = x_arc_roles
        if x_arc_proxy_secret is not None:
            _header_params['X-Arc-Proxy-Secret'] = x_arc_proxy_secret
        # process the form parameters
        # process the body parameter
        if provider_confirmation_repair_request is not None:
            _body_params = provider_confirmation_repair_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/v1/arc/cases/{case_id}/communications/{comm_id}/resolve-provider-confirmation',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


